import React, { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

type Language = 'en' | 'si' | 'ta';

interface Translations {
  [key: string]: { en: string; si: string };
}

const translations: Translations = {
  // Login
  'HMCS Banking': { en: 'HMCS Banking', si: 'HMCS බැංකුව' },
  'Secure Portal Access': { en: 'Secure Portal Access', si: 'සුරක්ෂිත පිවිසුම' },
  'Username': { en: 'Username', si: 'පරිශීලක නාමය' },
  'Password': { en: 'Password', si: 'මුරපදය' },
  'Sign In to Secure Portal': { en: 'Sign In to Secure Portal', si: 'පද්ධතියට ඇතුළු වන්න' },
  'Enter your username': { en: 'Enter your username', si: 'පරිශීලක නාමය ඇතුළත් කරන්න' },
  'Authenticating...': { en: 'Authenticating...', si: 'තහවුරු කරමින්...' },
  'Hikkaduwa Multi-Purpose Co-operative Society Ltd.': { en: 'Hikkaduwa Multi-Purpose Co-operative Society Ltd.', si: 'හික්කඩුව විවිධ සේවා සමුපකාර සමිතිය' },
  '© 2026 INTEGRATED BANKING SYSTEM': { en: '© 2026 INTEGRATED BANKING SYSTEM', si: '© 2026 ඒකාබද්ධ බැංකු පද්ධතිය' },

  // Branches
  'Hikkaduwa Branch': { en: 'Hikkaduwa Branch', si: 'හික්කඩුව ශාඛාව' },
  'Dodanduwa Branch': { en: 'Dodanduwa Branch', si: 'දොඩන්දූව ශාඛාව' },
  'Rathgama Branch': { en: 'Rathgama Branch', si: 'රත්ගම ශාඛාව' },
  'Seenigama Branch': { en: 'Seenigama Branch', si: 'සීනිගම ශාඛාව' },
  'Thiranagama Branch': { en: 'Thiranagama Branch', si: 'තිරණගම ශාඛාව' },
  'Peraliya Branch': { en: 'Peraliya Branch', si: 'පෙරලිය ශාඛාව' },
  'Kalupe Branch': { en: 'Kalupe Branch', si: 'කලුපේ ශාඛාව' },
  'Gonapinuwala Branch': { en: 'Gonapinuwala Branch', si: 'ගෝනාපීනුවල ශාඛාව' },
  'Dodangoda Branch': { en: 'Dodangoda Branch', si: 'දොඩංගොඩ ශාඛාව' },
  'දොඩංගොඩ ශාඛාව': { en: 'Dodangoda Branch', si: 'දොඩංගොඩ ශාඛාව' },
  'Baddegama Main Branch': { en: 'Baddegama Main Branch', si: 'බද්දේගම ප්‍රධාන ශාඛාව' },
  'බද්දේගම ප්‍රධාන ශාඛාව': { en: 'Baddegama Main Branch', si: 'බද්දේගම ප්‍රධාන ශාඛාව' },
  'Galle Main Branch': { en: 'Galle Main Branch', si: 'ගාල්ල ප්‍රධාන ශාඛාව' },
  'ගාල්ල ප්‍රධාන ශාඛාව': { en: 'Galle Main Branch', si: 'ගාල්ල ප්‍රධාන ශාඛාව' },
  'සන්දරවල ශාඛාව': { en: 'Sandarawala Branch', si: 'සන්දරවල ශාඛාව' },
  'පැරෑලිය ශාඛාව': { en: 'Peraliya Branch', si: 'පැරෑලිය ශාඛාව' },

  // Common
  'Dashboard': { en: 'Dashboard', si: 'පාලක පුවරුව' },
  'Branch Online': { en: 'Branch Online', si: 'ශාඛාව මාර්ගගතයි' },
  'Welcome back': { en: 'Welcome back', si: 'නැවත සාදරයෙන් පිළිගනිමු' },
  'Here\'s your work summary.': { en: 'Here\'s your work summary.', si: 'මෙන්න ඔබගේ වැඩ සාරාංශය.' },
  'Sign Out': { en: 'Sign Out', si: 'ඉවත් වන්න' },
  'Cancel': { en: 'Cancel', si: 'අවලංගු කරන්න' },
  'Processing...': { en: 'Processing...', si: 'සැකසෙමින් පවතී...' },
  'Search by name or NIC...': { en: 'Search by name or NIC...', si: 'නම හෝ හැඳුනුම්පත මගින් සොයන්න...' },
  'Search account number...': { en: 'Search account number...', si: 'ගිණුම් අංකය සොයන්න...' },

  // Sidebar labels
  'Overview': { en: 'Overview', si: 'දළ විශ්ලේෂණය' },
  'Members': { en: 'Members', si: 'සාමාජිකයින්' },
  'Savings Accounts': { en: 'Savings Accounts', si: 'ඉතුරුම් ගිණුම්' },
  'Fixed Deposits': { en: 'Fixed Deposits', si: 'ස්ථාවර තැන්පතු' },
  'Loan Accounts': { en: 'Loan Accounts', si: 'ණය ගිණුම්' },
  'Pawning (Gold Loans)': { en: 'Pawning (Gold Loans)', si: 'උකස් (රන් ණය)' },
  'Insurance Report': { en: 'Insurance Report', si: 'රක්ෂණ වාර්තාව' },
  'Loan Queue': { en: 'Loan Queue', si: 'ණය පෝලිම' },
  'Loan Committee': { en: 'Loan Committee', si: 'ණය කමිටුව' },
  'Loan Committee Approved': { en: 'Loan Committee Approved', si: 'කමිටුව අනුමත කළ ණය' },
  'Manager Approved': { en: 'Manager Approved', si: 'කළමනාකරු අනුමත කළ' },
  'Loan Committee Approval': { en: 'Loan Committee Approval', si: 'ණය කමිටු අනුමැතිය' },
  'Committee Approved': { en: 'Committee Approved', si: 'කමිටුව අනුමත කළ' },
  'All Loans': { en: 'All Loans', si: 'සියලුම ණය' },
  'Approvals': { en: 'Approvals', si: 'අනුමැතියන්' },
  'Vote on Loans': { en: 'Vote on Loans', si: 'ණය අනුමැතිය' },
  'Alerts': { en: 'Alerts', si: 'ඇඟවීම්' },
  
  // Dashboard Titles & Stats
  'Deposits vs Advances': { en: 'Deposits vs Advances', si: 'තැන්පතු සහ අත්තිකාරම්' },
  'Loan Portfolio Distribution': { en: 'Loan Portfolio Distribution', si: 'ණය ව්‍යාප්තිය' },
  'Liquidity Overview': { en: 'Liquidity Overview', si: 'ද්‍රවශීලතා දළ විශ්ලේෂණය' },
  'No active loans available for distribution.': { en: 'No active loans available for distribution.', si: 'පෙන්වීමට සක්‍රීය ණය නොමැත.' },
  'Total Members': { en: 'Total Members', si: 'මුළු සාමාජිකයින්' },
  'Non-members': { en: 'Non-members', si: 'සාමාජික නොවන' },
  'Savings': { en: 'Savings', si: 'ඉතුරුම්' },
  'Accounts': { en: 'Accounts', si: 'ගිණුම්' },
  'Fixed Deposits': { en: 'Fixed Deposits', si: 'ස්ථාවර තැන්පතු' },
  'FDs': { en: 'FDs', si: 'තැන්පතු' },
  'Outstanding Loans': { en: 'Outstanding Loans', si: 'ගෙවීමට ඇති ණය' },
  'Active Loans': { en: 'Active Loans', si: 'සක්‍රීය ණය' },
  'Pawning Advances': { en: 'Pawning Advances', si: 'උකස් අත්තිකාරම්' },
  'Active Tickets': { en: 'Active Tickets', si: 'සක්‍රීය උකස්' },
  'Active Members': { en: 'Active Members', si: 'ක්‍රියාකාරී සාමාජිකයින්' },
  'Total Accounts': { en: 'Total Accounts', si: 'මුළු ගිණුම්' },
  'Branch Members': { en: 'Branch Members', si: 'ශාඛා සාමාජිකයින්' },
  'Branch Accounts': { en: 'Branch Accounts', si: 'ශාඛා ගිණුම්' },
  
  // Tables
  'Account No.': { en: 'Account No.', si: 'ගිණුම් අංකය' },
  'Type': { en: 'Type', si: 'වර්ගය' },
  'Balance': { en: 'Balance', si: 'ශේෂය' },
  'Status': { en: 'Status', si: 'තත්ත්වය' },
  'Member': { en: 'Member', si: 'සාමාජිකයා' },
  'Membership No': { en: 'Membership No', si: 'සාමාජික අංකය' },
  'NIC': { en: 'NIC', si: 'හැඳුනුම්පත' },
  'Accounts': { en: 'Accounts', si: 'ගිණුම්' },
  'Action': { en: 'Action', si: 'ක්‍රියාව' },
  'No members found. Register the first member!': { en: 'No members found. Register the first member!', si: 'සාමාජිකයින් හමු නොවීය. පළමු සාමාජිකයා ලියාපදිංචි කරන්න!' },
  'No accounts found': { en: 'No accounts found', si: 'ගිණුම් කිසිවක් හමු නොවීය' },
  'Activity Details': { en: 'Activity Details', si: 'ක්‍රියාකාරකම් විස්තර' },
  'Reference ID': { en: 'Reference ID', si: 'යොමු අංකය' },
  'Amount': { en: 'Amount', si: 'මුදල' },
  'Balance After': { en: 'Balance After', si: 'පසු ශේෂය' },
  'Account No': { en: 'Account No', si: 'ගිණුම් අංකය' },
  'Fixed Deposit Account No': { en: 'Fixed Deposit Account No', si: 'Fixed Deposit ගිණුම් අංකය' },
  'Account Owner': { en: 'Account Owner', si: 'ගිණුම් හිමියා' },
  'Branch': { en: 'Branch', si: 'ගිණුම පවතින ශාඛාව' },
  'Timestamp': { en: 'Timestamp', si: 'දිනය සහ වේලාව' },
  'Close': { en: 'Close', si: 'වසා දමන්න' },
  'DEPOSIT': { en: 'Deposit', si: 'තැන්පතු' },
  'WITHDRAWAL': { en: 'Withdrawal', si: 'මුදල් ලබාගැනීම' },
  'NEW_SAVINGS': { en: 'New Savings Account', si: 'නව ඉතුරුම් ගිණුම' },
  'NEW_FD': { en: 'New Fixed Deposit', si: 'නව ස්ථාවර තැන්පතුව' },
  
  // Buttons
  'Open Account': { en: 'Open Account', si: 'ගිණුමක් විවෘත කරන්න' },
  'Transaction Successful': { en: 'Transaction Successful', si: 'ගනුදෙනුව සාර්ථකයි' },
  'Approval Requested': { en: 'Approval Requested', si: 'අනුමැතිය ඉල්ලා ඇත' },
  'Print Receipt': { en: 'Print Receipt', si: 'ලදුපත මුද්‍රණය' },
  'Txn ID:': { en: 'Txn ID:', si: 'ගනුදෙනු අංකය:' },
  'Request ID:': { en: 'Request ID:', si: 'ඉල්ලීම් අංකය:' },
  'New Balance:': { en: 'New Balance:', si: 'නව ශේෂය:' },
  'Current Balance:': { en: 'Current Balance:', si: 'වත්මන් ශේෂය:' },
  'Credited Amount:': { en: 'Credited Amount:', si: 'බැර කළ මුදල:' },
  'Deducted Interest:': { en: 'Deducted Interest:', si: 'අඩු කළ පොලිය:' },
  'Confirm Transaction': { en: 'Confirm Transaction', si: 'ගනුදෙනුව තහවුරු කරන්න' },
  'Confirm': { en: 'Confirm', si: 'තහවුරු කරන්න' },
  'Register Member': { en: 'Register Member', si: 'සාමාජිකයෙකු ලියාපදිංචි කරන්න' },
  'Opening...': { en: 'Opening...', si: 'විවෘත කරමින්...' },
  
  // Register Member Form
  'Register New Member': { en: 'Register New Member', si: 'නව සාමාජිකයෙකු ලියාපදිංචි කරන්න' },
  'Identification Details': { en: 'Identification Details / හැඳුනුම් තොරතුරු', si: 'Identification Details / හැඳුනුම් තොරතුරු' },
  'IDENTIFICATION DETAILS': { en: 'IDENTIFICATION DETAILS / හැඳුනුම් තොරතුරු', si: 'IDENTIFICATION DETAILS / හැඳුනුම් තොරතුරු' },
  'Age Category': { en: 'Age Category / වයස් කාණ්ඩය', si: 'Age Category / වයස් කාණ්ඩය' },
  'Adult (18+)': { en: 'Adult (18+) / වැඩිහිටි (18+)', si: 'Adult (18+) / වැඩිහිටි (18+)' },
  'Child (Under 18)': { en: 'Child (Under 18) / ළමා (18 ට අඩු)', si: 'Child (Under 18) / ළමා (18 ට අඩු)' },
  'Client ID': { en: 'Client ID / සේවාදායක අංකය', si: 'Client ID / සේවාදායක අංකය' },
  'National Identity Card (NIC)': { en: 'National Identity Card (NIC) / ජාතික හැඳුනුම්පත', si: 'National Identity Card (NIC) / ජාතික හැඳුනුම්පත' },
  'Guardian NIC': { en: 'Guardian NIC / භාරකරුගේ හැඳුනුම්පත', si: 'Guardian NIC / භාරකරුගේ හැඳුනුම්පත' },
  'Guardian ID': { en: 'Guardian ID / භාරකරුගේ අංකය', si: 'Guardian ID / භාරකරුගේ අංකය' },
  'Personal Information': { en: 'Personal Information / පුද්ගලික තොරතුරු', si: 'Personal Information / පුද්ගලික තොරතුරු' },
  'Full Name': { en: 'Full Name / සම්පූර්ණ නම', si: 'Full Name / සම්පූර්ණ නම' },
  'Full Name (English)': { en: 'Full Name (English) / සම්පූර්ණ නම (ඉංග්‍රීසි)', si: 'Full Name (English) / සම්පූර්ණ නම (ඉංග්‍රීසි)' },
  'Full Name (Sinhala/Tamil)': { en: 'Full Name (Sinhala/Tamil) / සම්පූර්ණ නම (සිංහල/දෙමළ)', si: 'Full Name (Sinhala/Tamil) / සම්පූර්ණ නම (සිංහල/දෙමළ)' },
  'Name with Initials': { en: 'Name with Initials / මුලකුරු සමඟ නම', si: 'Name with Initials / මුලකුරු සමඟ නම' },
  'Name in Sinhala (Optional)': { en: 'Name in Sinhala (Optional) / සිංහලෙන් නම (විකල්ප)', si: 'Name in Sinhala (Optional) / සිංහලෙන් නම (විකල්ප)' },
  'Date of Birth': { en: 'Date of Birth / උපන් දිනය', si: 'Date of Birth / උපන් දිනය' },
  'Gender': { en: 'Gender / ස්ත්‍රී පුරුෂ භාවය', si: 'Gender / ස්ත්‍රී පුරුෂ භාවය' },
  'Male': { en: 'Male / පුරුෂ', si: 'Male / පුරුෂ' },
  'Female': { en: 'Female / ස්ත්‍රී', si: 'Female / ස්ත්‍රී' },
  'Marital Status': { en: 'Marital Status / විවාහක/අවිවාහක බව', si: 'Marital Status / විවාහක/අවිවාහක බව' },
  'Married': { en: 'Married / විවාහක', si: 'Married / විවාහක' },
  'Unmarried': { en: 'Unmarried / අවිවාහක', si: 'Unmarried / අවිවාහක' },
  'Address': { en: 'Address / ලිපිනය', si: 'Address / ලිපිනය' },
  'Province': { en: 'Province / පළාත', si: 'Province / පළාත' },
  'Contact Number': { en: 'Contact Number / දුරකථන අංකය', si: 'Contact Number / දුරකථන අංකය' },
  'Photograph': { en: 'Photograph / ඡායාරූපය', si: 'Photograph / ඡායාරූපය' },
  'Digital Documents': { en: 'Digital Documents / ඩිජිටල් ලිපිලේඛන', si: 'Digital Documents / ඩිජිටල් ලිපිලේඛන' },
  'Registration Type': { en: 'Registration Type / ලියාපදිංචි වර්ගය', si: 'Registration Type / ලියාපදිංචි වර්ගය' },
  'Society Member': { en: 'Society Member', si: 'සමිතියේ සාමාජික' },
  'Society Account': { en: 'Society Account', si: 'සාමාජික ගිණුමක්' },
  'Non-Society Account': { en: 'Non-Society Account', si: 'සාමාජික නොවන ගිණුමක්' },
  'Non-Member': { en: 'Non-Member', si: 'සාමාජික නොවන' },
  'Select Person': { en: 'Select Person', si: 'පුද්ගලයා තෝරන්න' },
  'Membership Details': { en: 'Membership Details', si: 'සාමාජිකත්ව තොරතුරු' },
  // Account Types
  'Normal Savings (Samanaya 01)': { en: 'Normal (Samanaya 01) / සාමාන්‍ය 01', si: 'Normal (Samanaya 01) / සාමාන්‍ය 01' },
  'NORMAL': { en: 'Normal (Samanaya 01) / සාමාන්‍ය 01', si: 'Normal (Samanaya 01) / සාමාන්‍ය 01' },
  'Janasetha': { en: 'Janasetha / ජනසෙත', si: 'Janasetha / ජනසෙත' },
  'JANASETHA': { en: 'Janasetha / ජනසෙත', si: 'Janasetha / ජනසෙත' },
  'Dhana Yojana': { en: 'Dhana Yojana / ධන යෝජනා', si: 'Dhana Yojana / ධන යෝජනා' },
  'DHANA_YOJANA': { en: 'Dhana Yojana / ධන යෝජනා', si: 'Dhana Yojana / ධන යෝජනා' },
  'Vandana': { en: 'Vandana / වන්දනා', si: 'Vandana / වන්දනා' },
  'VANDANA': { en: 'Vandana / වන්දනා', si: 'Vandana / වන්දනා' },
  'Arunalu (Children)': { en: 'Arunalu / අරුණලු', si: 'Arunalu / අරුණලු' },
  'ARUNALU': { en: 'Arunalu / අරුණලු', si: 'Arunalu / අරුණලු' },
  'Ranthilina (Children)': { en: 'Ranthilina / රන්තිලින', si: 'Ranthilina / රන්තිලින' },
  'RANTHILINA': { en: 'Ranthilina / රන්තිලින', si: 'Ranthilina / රන්තිලින' },
  'Non-Members': { en: 'Non-Members', si: 'සාමාජික නොවන අය' },
  'Total Non-Members': { en: 'Total Non-Members', si: 'මුළු සාමාජික නොවන අය' },
  'Active Non-Members': { en: 'Active Non-Members', si: 'සක්‍රිය සාමාජික නොවන අය' },
  'Register Non-Member': { en: 'Register Non-Member', si: 'සාමාජික නොවන අය ලියාපදිංචි කරන්න' },
  'Share Amount (Rs.)': { en: 'Share Capital (Rs.)', si: 'කොටස් අරමුදල (රු.)' },
  'Number of Shares': { en: 'Number of Shares', si: 'මිලදී ගත් කොටස් ප්‍රමාණය' },
  'Belongs to another society?': { en: 'Belongs to another society?', si: 'වෙනත් සමිතියකට අයත්ද?' },
  'Other Society Name': { en: 'Other Society Name', si: 'වෙනත් සමිතියේ නම' },
  'Authorize & Register': { en: 'Authorize & Register', si: 'අනුමත කර ලියාපදිංචි කරන්න' },

  // Open Account Form
  'Open Savings Account': { en: 'Open Savings Account', si: 'ඉතුරුම් ගිණුමක් විවෘත කරන්න' },
  'Select Member': { en: 'Select Member', si: 'සාමාජිකයා තෝරන්න' },
  '-- Select Member --': { en: '-- Select Member --', si: '-- සාමාජිකයා තෝරන්න --' },
  'Members (Samajika)': { en: 'Members (Samajika)', si: 'සාමාජිකයින් (සාමාජික)' },
  'Non-Members (Customers)': { en: 'Non-Members (Customers)', si: 'සාමාජික නොවන (පාරිභෝගිකයින්)' },
  'Account Type': { en: 'Account Type', si: 'ගිණුම් වර්ගය' },
  'Regular Savings': { en: 'Regular Savings', si: 'සාමාන්‍ය ඉතුරුම්' },
  "Children's Account": { en: "Children's Account", si: 'ළමා ගිණුම' },
  'Senior Citizen': { en: 'Senior Citizen', si: 'ජ්‍යෙෂ්ඨ පුරවැසි' },
  'Fixed Deposit': { en: 'Fixed Deposit', si: 'ස්ථාවර තැන්පතුව' },
  'Initial Deposit (Rs.)': { en: 'Initial Deposit (Rs.)', si: 'මූලික තැන්පතුව (රු.)' },
  'Child Information': { en: 'Child Information', si: 'ළමා තොරතුරු' },
  "Child's Name *": { en: "Child's Name *", si: 'ළමයාගේ නම *' },
  'Birth Certificate No. *': { en: 'Birth Certificate No. *', si: 'උප්පැන්න සහතික අංකය *' },
  'Date of Birth *': { en: 'Date of Birth *', si: 'උපන් දිනය *' },

  // Values
  'REGULAR': { en: 'REGULAR', si: 'සාමාන්‍ය' },
  'CHILD': { en: 'CHILD', si: 'ළමා' },
  'SENIOR': { en: 'SENIOR', si: 'ජ්‍යෙෂ්ඨ' },
  'FIXED': { en: 'FIXED', si: 'ස්ථාවර' },
  'ACTIVE': { en: 'ACTIVE', si: 'ක්‍රියාකාරී' },
  'PENDING': { en: 'PENDING', si: 'පොරොත්තු' },
  
  // Roles
  'Senior Officer': { en: 'Senior Officer', si: 'ජ්‍යෙෂ්ඨ නිලධාරී' },
  'Branch Manager': { en: 'Branch Manager', si: 'ශාඛා කළමනාකරු' },
  'Bank Service Manager': { en: 'Bank Service Manager', si: 'බැංකු සේවා කළමනාකරු' },
  'Teller': { en: 'Teller', si: 'මුදල් අයකැමි' },
  'Central Loan Committee': { en: 'Central Loan Committee', si: 'මධ්‍යම ණය කමිටුව' },
  
  // Admin Dashboard
  'System Administration Panel': { en: 'System Administration Panel', si: 'පද්ධති පරිපාලන පුවරුව' },
  'HMCS Integrated Banking System · All 8 Branches': { en: 'HMCS Integrated Banking System · All 8 Branches', si: 'HMCS ඒකාබද්ධ බැංකු පද්ධතිය · ශාඛා 8ම' },
  '8 / 8 Branches Online': { en: '8 / 8 Branches Online', si: 'ශාඛා 8/8 මාර්ගගතයි' },
  'Total System Users': { en: 'Total System Users', si: 'මුළු පද්ධති පරිශීලකයින්' },
  'Across all branches': { en: 'Across all branches', si: 'සියලුම ශාඛා හරහා' },
  'Active Branches': { en: 'Active Branches', si: 'ක්‍රියාකාරී ශාඛා' },
  'All online': { en: 'All online', si: 'සියල්ල මාර්ගගතයි' },
  'System Uptime': { en: 'System Uptime', si: 'පද්ධති ක්‍රියාකාරී කාලය' },
  'Last 45 days': { en: 'Last 45 days', si: 'පසුගිය දින 45' },
  'Daily Backup': { en: 'Daily Backup', si: 'දෛනික උපස්ථය' },
  'Today 02:00 AM': { en: 'Today 02:00 AM', si: 'අද පෙ.ව 02:00' },
  'HMCS Bank': { en: 'HMCS Bank', si: 'HMCS බැංකුව' },
  'System Administration': { en: 'System Administration', si: 'පද්ධති පරිපාලනය' },
  'Live Branch Network — Click to Manage': { en: 'Live Branch Network — Click to Manage', si: 'සජීවී ශාඛා ජාලය — කළමනාකරණය කිරීමට ක්ලික් කරන්න' },
  'Online': { en: 'Online', si: 'මාර්ගගතයි' },
  'user': { en: 'user', si: 'පරිශීලකයෙක්' },
  'users': { en: 'users', si: 'පරිශීලකයින්' },
  'System Activity Log': { en: 'System Activity Log', si: 'පද්ධති ක්‍රියාකාරකම් ලොගය' },
  
  // Branch Detail view
  'staff accounts': { en: 'staff accounts', si: 'කාර්ය මණ්ඩල ගිණුම්' },
  'Staff & Users': { en: 'Staff & Users', si: 'කාර්ය මණ්ඩලය සහ පරිශීලකයින්' },
  'Interest Rates': { en: 'Interest Rates', si: 'පොලී අනුපාත' },
  'Account Types': { en: 'Account Types', si: 'ගිණුම් වර්ග' },
  'Add Type': { en: 'Add Type', si: 'අලුතින් එක් කරන්න' },
  'Branch Config': { en: 'Branch Config', si: 'ශාඛා සැකසුම්' },
  'Add User': { en: 'Add User', si: 'පරිශීලක එක් කරන්න' },
  'Role': { en: 'Role', si: 'භූමිකාව' },
  'Actions': { en: 'Actions', si: 'ක්‍රියා' },
  'Edit': { en: 'Edit', si: 'සංස්කරණය' },
  'Delete': { en: 'Delete', si: 'මකන්න' },
  'Active': { en: 'Active', si: 'ක්‍රියාකාරී' },
  'Save Changes': { en: 'Save Changes', si: 'වෙනස්කම් සුරකින්න' },
  'Create User': { en: 'Create User', si: 'පරිශීලක සාදන්න' },
  'Branch Interest & Loan Rates': { en: 'Branch Interest & Loan Rates', si: 'ශාඛා පොලී සහ ණය අනුපාත' },
  'FD Interest Rate (%)': { en: 'FD Interest Rate (%)', si: 'ස්ථාවර තැන්පතු පොලී අනුපාතය (%)' },
  'FD Bonus Rate (%)': { en: 'FD Bonus Rate (%)', si: 'ස්ථාවර තැන්පතු ප්‍රසාද අනුපාතය (%)' },
  'Pawning Rate (% p.a.)': { en: 'Pawning Rate (% p.a.)', si: 'උකස් අනුපාතය (වාර්ෂික %)' },
  'Max Loan Term (Months)': { en: 'Max Loan Term (Months)', si: 'උපරිම ණය කාලය (මාස)' },
  'Save Rates': { en: 'Save Rates', si: 'අනුපාත සුරකින්න' },
  'Add Savings Type': { en: 'Add Savings Type', si: 'ඉතුරුම් වර්ගය එක් කරන්න' },
  'Code': { en: 'Code', si: 'කේතය' },
  'Account Target': { en: 'Account Target', si: 'ගිණුම් ඉලක්කය' },
  'English Name': { en: 'English Name', si: 'ඉංග්‍රීසි නම' },
  'Sinhala Name': { en: 'Sinhala Name', si: 'සිංහල නම' },
  'Adult': { en: 'Adult', si: 'වැඩිහිටි' },
  'Save': { en: 'Save', si: 'සුරකින්න' },
  'Manage Savings Account Types': { en: 'Manage Savings Account Types', si: 'ඉතුරුම් ගිණුම් වර්ග කළමනාකරණය' },
  'Target': { en: 'Target', si: 'ඉලක්කය' },
  'English': { en: 'English', si: 'ඉංග්‍රීසි' },
  'Sinhala': { en: 'Sinhala', si: 'සිංහල' },
  'Branch Information': { en: 'Branch Information', si: 'ශාඛා තොරතුරු' },
  'Branch Name': { en: 'Branch Name', si: 'ශාඛාවේ නම' },
  'Location': { en: 'Location', si: 'ස්ථානය' },
  'Branch Status': { en: 'Branch Status', si: 'ශාඛා තත්ත්වය' },
  'Mark branch as Active / Inactive': { en: 'Mark branch as Active / Inactive', si: 'ශාඛාව ක්‍රියාකාරී / අක්‍රිය ලෙස ලකුණු කරන්න' },
  'Inactive branches cannot process transactions.': { en: 'Inactive branches cannot process transactions.', si: 'අක්‍රිය ශාඛාවන්ට ගනුදෙනු සිදු කළ නොහැක.' },
  'Save Config': { en: 'Save Config', si: 'සැකසුම් සුරකින්න' },
  'Edit User Profile': { en: 'Edit User Profile', si: 'පරිශීලක පැතිකඩ සංස්කරණය' },
  'New User —': { en: 'New User —', si: 'නව පරිශීලක —' },
  'Temporary Password': { en: 'Temporary Password', si: 'තාවකාලික මුරපදය' },
  'New Password (leave blank to keep)': { en: 'New Password (leave blank to keep)', si: 'නව මුරපදය (තබා ගැනීමට හිස්ව තබන්න)' },
  'Leave empty to keep existing': { en: 'Leave empty to keep existing', si: 'පවතින එක තබා ගැනීමට හිස්ව තබන්න' },
  'Set password': { en: 'Set password', si: 'මුරපදය සකසන්න' },
  'No staff accounts yet.': { en: 'No staff accounts yet.', si: 'තවමත් කාර්ය මණ්ඩල ගිණුම් නොමැත.' },
  'Click "Add User" to create the first account for this branch.': { en: 'Click "Add User" to create the first account for this branch.', si: 'මෙම ශාඛාව සඳහා පළමු ගිණුම සෑදීමට "පරිශීලක එක් කරන්න" ක්ලික් කරන්න.' },

  // Rates Categories
  'Savings': { en: 'Savings', si: 'ඉතුරුම්' },
  'Loans': { en: 'Loans', si: 'ණය' },
  'Pawning': { en: 'Pawning', si: 'උකස්' },
  'General / Shares': { en: 'General / Shares', si: 'සාමාන්‍ය / කොටස්' },
  'Total Earnings': { en: 'Total Earnings', si: 'මුළු ඉපැයීම්' },
  'Product / Type': { en: 'Product / Type', si: 'නිෂ්පාදනය / වර්ගය' },
  'Interest Rate / Value': { en: 'Interest Rate / Value', si: 'පොලී අනුපාතය / අගය' },
  'All': { en: 'All', si: 'සියල්ල' },
  'Rs.': { en: 'Rs.', si: 'රු.' },
  'Savings Interest Rates (% p.a.)': { en: 'Savings Interest Rates (% p.a.)', si: 'ඉතුරුම් පොලී අනුපාත (වාර්ෂික %)' },
  'No savings account types found.': { en: 'No savings account types found.', si: 'ඉතුරුම් ගිණුම් වර්ග කිසිවක් හමු නොවීය.' },
  'Fixed Deposit Rates (% p.a.)': { en: 'Fixed Deposit Rates (% p.a.)', si: 'ස්ථාවර තැන්පතු අනුපාත (වාර්ෂික %)' },
  '3 Months': { en: '3 Months', si: 'මාස 3' },
  '6 Months': { en: '6 Months', si: 'මාස 6' },
  '1 Year': { en: '1 Year', si: 'අවුරුදු 1' },
  'Senior Citizen (1 Year)': { en: 'Senior Citizen (1 Year)', si: 'ජ්‍යෙෂ්ඨ පුරවැසි (අවුරුදු 1)' },
  'Loan Rates (% p.a.)': { en: 'Loan Rates (% p.a.)', si: 'ණය පොලී අනුපාත (වාර්ෂික %)' },
  'Personal Loan': { en: 'Personal Loan', si: 'පුද්ගලික ණය' },
  'Housing Loan': { en: 'Housing Loan', si: 'නිවාස ණය' },
  'Business Loan': { en: 'Business Loan', si: 'ව්‍යාපාරික ණය' },
  'Pawning Rates & Terms': { en: 'Pawning Rates & Terms', si: 'උකස් අනුපාත සහ නියමයන්' },
  'Pawning Interest Rate (% p.a.)': { en: 'Pawning Interest Rate (% p.a.)', si: 'උකස් පොලී අනුපාතය (වාර්ෂික %)' },
  'Advance per Gold Sovereign (Rs.)': { en: 'Advance per Gold Sovereign (Rs.)', si: 'රන් පවුමකට අත්තිකාරම් (රු.)' },
  'Advance per Gold Sovereign': { en: 'Advance per Gold Sovereign', si: 'රන් පවුමකට අත්තිකාරම්' },
  'Pawning Approvals': { en: 'Pawning Approvals', si: 'උකස් අනුමැතීන්' },
  // Save All Rates
  'Save All Rates': { en: 'Save All Rates', si: 'සියලුම අනුපාත සුරකින්න' },
  'Branch updated successfully!': { en: 'Branch updated successfully!', si: 'ශාඛාව සාර්ථකව යාවත්කාලීන කරන ලදී!' },
  'Failed to update branch': { en: 'Failed to update branch', si: 'ශාඛාව යාවත්කාලීන කිරීම අසාර්ථකයි' },
  'Saving...': { en: 'Saving...', si: 'සුරකිමින්...' },
  
  // Locations
  'Hikkaduwa Town': { en: 'Hikkaduwa Town', si: 'හික්කඩුව නගරය' },
  'Dodanduwa': { en: 'Dodanduwa', si: 'දොඩන්දූව' },
  'Rathgama': { en: 'Rathgama', si: 'රත්ගම' },
  'Seenigama': { en: 'Seenigama', si: 'සීනිගම' },
  'Thiranagama': { en: 'Thiranagama', si: 'තිරණගම' },
  'Peraliya': { en: 'Peraliya', si: 'පේරලිය' },
  'Kalupe': { en: 'Kalupe', si: 'කළුපේ' },
  'Gonapinuwala': { en: 'Gonapinuwala', si: 'ගොනාපීනුවල' },
  'Are you sure?': {
    en: 'Are you sure?',
    si: 'Are you sure? / ඔබට විශ්වාසද?',
    ta: 'நீங்கள் உறுதியாக இருக்கிறீர்களா?'
  },
  'You want to mark this comment as resolved?': {
    en: 'You want to mark this comment as resolved?',
    si: 'You want to mark this comment as resolved? / ඔබට මෙම සටහන විසඳුවා ලෙස සලකුණු කිරීමට අවශ්‍යද?',
    ta: 'இந்தக் கருத்தைத் தீர்க்கப்பட்டதாகக் குறிக்க விரும்புகிறீர்களா?'
  },
  'Yes, mark as resolved': {
    en: 'Yes, mark as resolved',
    si: 'Yes, mark as resolved / ඔව්',
    ta: 'ஆம், குறிக்கவும்'
  },
  'Resolved!': {
    en: 'Resolved!',
    si: 'Resolved! / විසඳුවා!',
    ta: 'தீர்க்கப்பட்டது!'
  },
  'Comment successfully marked as resolved!': {
    en: 'Comment successfully marked as resolved!',
    si: 'Comment successfully marked as resolved! / සටහන සාර්ථකව විසඳුවා ලෙස සලකුණු කරන ලදී!',
    ta: 'கருத்து வெற்றிகரமாகத் தீர்க்கப்பட்டதாகக் குறிக்கப்பட்டது!'
  },
  'Error!': {
    en: 'Error!',
    si: 'Error! / දෝෂයක්!',
    ta: 'பிழை!'
  },
  'Failed to resolve comment. Please try again.': {
    en: 'Failed to resolve comment. Please try again.',
    si: 'Failed to resolve comment. / සටහන විසඳුවා ලෙස සලකුණු කිරීමට නොහැකි විය.',
    ta: 'கருத்தைத் தீர்ப்பதில் தோல்வி. மீண்டும் முயற்சிக்கவும்.'
  },
};


const tamilDict: Record<string, string> = {
  "Deposits vs Advances": "வைப்புகள் மற்றும் முன்பணங்கள் (Deposits vs Advances)",
  "Loan Portfolio Distribution": "கடன் விநியோகம் (Loan Portfolio)",
  "Liquidity Overview": "பணப்புழக்க மேலோட்டம் (Liquidity Overview)",
  "No active loans available for distribution.": "விநியோகத்திற்கு செயலில் உள்ள கடன்கள் எதுவும் இல்லை.",
  "Non-members": "உறுப்பினர் அல்லாதவர்கள் (Non-members)",
  "Savings": "சேமிப்பு (Savings)",
  "Accounts": "கணக்குகள் (Accounts)",
  "Fixed Deposits": "நிலையான வைப்புத்தொகைகள் (Fixed Deposits)",
  "FDs": "வைப்புத்தொகைகள் (FDs)",
  "Outstanding Loans": "செலுத்த வேண்டிய கடன்கள் (Outstanding Loans)",
  "Active Loans": "செயலில் உள்ள கடன்கள் (Active Loans)",
  "Pawning Advances": "அடகு முன்பணங்கள் (Pawning Advances)",
  "Active Tickets": "செயலில் உள்ள அடகுகள் (Active Tickets)",
  "HMCS Banking": "HMCS வங்கி (HMCS Banking)",
  "Secure Portal Access": "பாதுகாப்பான போர்டல் அணுகல் (Secure Portal Access)",
  "Username": "பயனர் பெயர் (Username)",
  "Password": "கடவுச்சொல் (Password)",
  "Sign In to Secure Portal": "உள்நுழையவும் (Sign In)",
  "Enter your username": "பயனர் பெயரை உள்ளிடவும் (Enter Username)",
  "Authenticating...": "உறுதிப்படுத்தப்படுகிறது... (Authenticating...)",
  "Hikkaduwa Multi-Purpose Co-operative Society Ltd.": "ஹிக்கடுவ பல்நோக்கு கூட்டுறவு சங்கம் லிமிடெட் (HMCS)",
  "© 2026 INTEGRATED BANKING SYSTEM": "© 2026 ஒருங்கிணைந்த வங்கி அமைப்பு (Integrated Banking)",
  "Hikkaduwa Branch": "ஹிக்கடுவ கிளை (Hikkaduwa Branch)",
  "Dodanduwa Branch": "தொடந்துவ கிளை (Dodanduwa Branch)",
  "Rathgama Branch": "ரத்கம கிளை (Rathgama Branch)",
  "Seenigama Branch": "சீனிகம கிளை (Seenigama Branch)",
  "Thiranagama Branch": "திரணகம கிளை (Thiranagama Branch)",
  "Peraliya Branch": "பெரலிய கிளை (Peraliya Branch)",
  "Kalupe Branch": "கலுபே கிளை (Kalupe Branch)",
  "Gonapinuwala Branch": "கோனாபினுவல கிளை (Gonapinuwala Branch)",
  "Dodangoda Branch": "தொடாங்கொட கிளை (Dodangoda Branch)",
  "Baddegama Main Branch": "பத்தேகம பிரதான கிளை (Baddegama Branch)",
  "Galle Main Branch": "காலி பிரதான கிளை (Galle Branch)",
  "සන්දරවල ශාඛාව": "சந்தரவல கிளை (Sandarawala Branch)",
  "පැරෑලිය ශාඛාව": "பெரலிய கிளை (Peraliya Branch)",
  "Dashboard": "டாஷ்போர்டு (Dashboard)",
  "Total Members": "மொத்த உறுப்பினர்கள் (Total Members)",
  "Active Members": "செயலில் உள்ள உறுப்பினர்கள் (Active Members)",
  "Total Accounts": "மொத்த கணக்குகள் (Total Accounts)",
  "Account No.": "கணக்கு எண் (Account No.)",
  "Type": "வகை (Type)",
  "Balance": "இருப்பு (Balance)",
  "Status": "நிலை (Status)",
  "Member": "உறுப்பினர் (Member)",
  "Action": "செயல்பாடு (Action)",
  "Open Account": "கணக்கு ஆரம்பிக்கவும் (Open Account)",
  "Register Member": "உறுப்பினர் பதிவு (Register Member)",
  "Deposit Cash": "பணம் வைப்பு (Deposit Cash)",
  "Withdraw Cash": "பணம் திரும்பப் பெறல் (Withdraw Cash)",
  "Welcome back": "மீண்டும் வருக (Welcome back)",
  "Sign Out": "வெளியேறவும் (Sign Out)",
  "Branch Online": "கிளை ஆன்லைன் (Branch Online)",
  "Reference ID": "குறிப்பு ஐடி (Reference ID)",
  "Amount": "தொகை (Amount)",
  "Balance After": "இருப்பு பின் (Balance After)",
  "Account Owner": "கணக்கு உரிமையாளர் (Account Owner)",
  "Branch": "கிளை (Branch)",
  "Timestamp": "நேரம் (Timestamp)",
  "Close": "மூடவும் (Close)",
  "Deposit": "வைப்பு (Deposit)",
  "Withdrawal": "திரும்பப் பெறல் (Withdrawal)",
  "DEPOSIT": "வைப்பு (Deposit)",
  "WITHDRAWAL": "திரும்பப் பெறல் (Withdrawal)",
  "NEW_SAVINGS": "புதிய சேமிப்புக் கணக்கு (New Savings)",
  "NEW_FD": "புதிய நிலையான வைப்பு (New FD)",
  "Activity Details": "நடவடிக்கை விவரங்கள் (Activity Details)",
  "Confirm Transaction": "பரிவர்த்தனையை உறுதிப்படுத்தவும் (Confirm Transaction)",
  "Confirm": "உறுதிப்படுத்தவும் (Confirm)",
  "Cancel": "ரத்துசெய் (Cancel)",
  "Next": "அடுத்தது (Next)",
  "OPENED DATE": "ஆரம்பிக்கப்பட்ட தேதி (Opened Date)",
  "Opened Date": "ஆரம்பிக்கப்பட்ட தேதி (Opened Date)",
  "Maturity Date": "முதிர்வு தேதி (Maturity Date)",
  "Interest Rate": "வட்டி விகிதம் (Interest Rate)",
  "Principal Amount": "அசல் தொகை (Principal Amount)",
  "FD Number": "நிலையான வைப்பு எண் (FD Number)",
  "FD No": "நிலையான வைப்பு எண் (FD No)",
  "Category": "வகை (Category)",
  "Term": "காலம் (Term)",
  "Account Type": "கணக்கு வகை (Account Type)",
  "Individual": "தனி நபர் (Individual)",
  "Joint": "கூட்டுக் கணக்கு (Joint)",
  "Search Member": "உறுப்பினரைத் தேடு (Search Member)",
  "ගිණුම පවතින ශාඛාව": "கணக்கு இருக்கும் கிளை (Branch)",
  "සමන්ත සෙනෙෂ්": "சமந்த செனேஷ் (Samantha Senesh)",
  "Overview": "மேலோட்டம் (Overview)",
  "Users & Members": "உறுப்பினர்கள் (Members)",
  "Members": "உறுப்பினர்கள் (Members)",
  "Non-Members": "உறுப்பினர் அல்லாதவர்கள் (Non-Members)",
  "Savings Accounts": "சேமிப்புக் கணக்குகள் (Savings Accounts)",
  "Fixed Deposits": "நிலையான வைப்புகள் (Fixed Deposits)",
  "Loan Accounts": "கடன் கணக்குகள் (Loan Loans)",
  "Pawning (Gold Loans)": "அடகு (Pawning)",
  "Insurance Report": "காப்புறுதி அறிக்கை (Insurance Report)",
  "Cash Transactions": "பணப் பரிவர்த்தனைகள் (Cash Transactions)",
  "General Ledger": "பொதுப் பேரேடு (General Ledger)",
  "Interest Rates": "வட்டி விகிதங்கள் (Interest Rates)",
  "CUSTOMER RELATIONS": "வாடிக்கையாளர் உறவுகள் (Customer Relations)",
  "CORE BANKING FACILITIES": "முக்கிய வங்கிச் சேவைகள் (Core Banking)",
  "DAILY OPERATIONS": "தினசரி செயல்பாடுகள் (Daily Operations)",
  "INFORMATION": "தகவல் (Information)",
  "Fixed Deposit Account No": "நிலையான வைப்பு கணக்கு எண் (Fixed Deposit Account No)",
  "විවිධ සේවා සමුපකාර සමිතිය": "Multi-Purpose Cooperative Society / விவித சேவா கூட்டுறவு சங்கம்",
  "මුදල් ඉතිරිකිරීමේ තැන්පත් ගිණුම් පෝරමය": "Savings Deposit Account Form / சேமிப்பு வைப்பு கணக்கு படிவம்",
  "සමාජික ගිණුමක්": "Member Account / உறுப்பினர் கணக்கு",
  "සමාජික නොවන ගිණුමක්": "Non-Member Account / உறுப்பினர் அல்லாத கணக்கு",
  "දිනය:": "Date / தேதி:",
  "ආයතනික": "Institutional / நிறுவன",
  "අයදුම්කරු": "Applicant / விண்ணப்பதாரர்",
  "සාක්ෂි": "Witness / சாட்சி",
  "තැන්පතු": "Deposit / வைப்பு",
  "ගිණුම් වර්ගීකරණය": "Account Classification / கணக்கு வகைப்படுத்தல்",
  "අයදුම්කරුගේ වර්ගය (Client Type)": "Client Type / விண்ணப்பதாரர் வகை",
  "වැඩිහිටි (Adult)": "Adult / பெரியவர்",
  "ළමා (Child)": "Child / சிறுவர்",
  "ගිණුම් ස්වභාවය (Account Mode)": "Account Mode / கணக்கின் தன்மை",
  "තනි ගිණුමක් (Single Account)": "Single Account / தனி கணக்கு",
  "හවුල් ගිණුමක් (Joint Account)": "Joint Account / கூட்டுக் கணக்கு",
  "ළමා ගිණුම් හවුල් ගිණුම් ලෙස විවෘත කළ නොහැක.": "Child accounts cannot be joint / சிறுவர் கணக்குகளை கூட்டுக் கணக்குகளாக திறக்க முடியாது.",
  "ගිණුම් අංකය (Account Number)": "Account Number / கணக்கு எண்",
  "උදා: ACC-123456": "e.g., ACC-123456 / உ-ம்: ACC-123456",
  "ගිණුම ආරම්භ කළ දිනය (Opened Date)": "Opened Date / கணக்கு தொடங்கப்பட்ட தேதி",
  "මෙය පැරණි ගිණුමක් පද්ධතියට ඇතුළත් කිරීමකි (Old Account Migration)": "Old Account Migration / இது பழைய கணக்கை கணினியில் சேர்த்தலாகும்",
  "* එබැවින් 4 වන පියවරේදී ලබා ගන්නේ වර්තමාන ශේෂය පමණි.": "* Therefore, only the current balance is taken in step 4. / * எனவே 4வது படியில் தற்போதைய நிலுவை மட்டுமே பெறப்படும்.",
  "පසුපසට (Back)": "Back / பின்செல்",
  "ඉදිරියට (Next)": "Next / அடுத்து",
  "ගිණුම සකසමින් පවතී...": "Processing Account... / கணக்கு செயலாக்கப்படுகிறது...",
  "ගිණුම විවෘත කරන්න (Open Account)": "Open Account / கணக்கைத் திற",
  "Open Savings Account": "Open Savings Account / சேமிப்பு கணக்கைத் திற",
  "Society Account": "Society Account / சங்கக் கணக்கு",
  "Non-Society Account": "Non-Society Account / சங்கமல்லாத கணக்கு",
  "Registration Type": "Registration Type / பதிவு வகை",
  "සාමාජිකයෙකු සොයන්න (Search Member)": "Search Member / உறுப்பினரைத் தேடுக",
  "පුද්ගලයෙකු සොයන්න (Search Non-Member)": "Search Non-Member / உறுப்பினர் அல்லாதவரைத் தேடுக",
  "උප්පැන්න සහතික අංකය / නම / සාමාජික අංකය...": "Birth Certificate No / Name / Member No...",
  "ජා.හැ.අ (NIC) / නම / සාමාජික අංකය...": "NIC / Name / Member No...",
  "සොයන්න": "Search / தேடுக",
  "ප්‍රතිඵල": "Results / முடிவுகள்",
  "ක් හමුවිය": "found / கிடைத்தன",
  "වසන්න": "Close / மூடுக",
  "ළමා ගිණුම් සඳහා ගැලපෙන ප්‍රතිඵල නොමැත.": "No matching results for minor accounts / சிறுவர் கணக்குகளுக்கு பொருத்தமான முடிவுகள் இல்லை.",
  "වැඩිහිටි ගිණුම් සඳහා ගැලපෙන ප්‍රතිඵල නොමැත.": "No matching results for adult accounts / பெரியவர் கணக்குகளுக்கு பொருத்தமான முடிவுகள் இல்லை.",
  "1. පළමුවන අයදුම්කරුගේ විස්තර": "1. 1st Applicant Details / 1வது விண்ணப்பதாரர் விவரங்கள்",
  "1. දරුවාගේ (Minor) මූලික විස්තර": "1. Minor's Basic Details / சிறுவரின் அடிப்படை விவரங்கள்",
  "නම සම්පූර්ණයෙන් (Full Name)": "Full Name / முழுப் பெயர்",
  "උපන් දිනය (DOB)": "DOB / பிறந்த தேதி",
  "වයස (Age)": "Age / வயது",
  "පුරවැසි හැඳුනුම්පත් අංකය (NIC No)": "NIC No / தேசிய அடையாள அட்டை எண்",
  "උප්පැන්න සහතිකයේ ලියාපදිංචි අංකය": "Birth Certificate Reg No / பிறப்புச் சான்றிதழ் பதிவு எண்",
  "රක්ෂාව (Occupation)": "Occupation / தொழில்",
  "ලිපිනය (Address)": "Address / முகவரி",
  "2. මව/පිය හෝ නීත්යානුකූල භාරකරුගේ විස්තර (Guardian)": "2. Guardian Details / பாதுகாவலர் விவரங்கள்",
  "2. දෙවන අයදුම්කරුගේ විස්තර": "2. 2nd Applicant Details / 2வது விண்ணப்பதாரர் விவரங்கள்",
  "නම සම්පූර්ණයෙන්": "Full Name / முழுப் பெயர்",
  "පුරවැසි හැඳුනුම්පත් අංකය (NIC)": "NIC / தே.அ.அ எண்",
  "රක්ෂාව සහ වයස": "Occupation & Age / தொழில் மற்றும் வயது",
  "රක්ෂාව": "Occupation / தொழில்",
  "වයස": "Age / வயது",
  "ලිපිනය": "Address / முகவரி",
  "3. තෙවන අයදුම්කරුගේ විස්තර (Optional)": "3. 3rd Applicant Details (Optional) / 3வது விண்ணப்பதாரர் விவரங்கள்",
  "මුදල් ආපසු ලබාගැනීමේ රීති (Mode of Operation)": "Mode of Operation / செயல்படும் முறை",
  "මුදල් ආපසු ලබාගන්නේ කවුරුන් විසින්ද?": "Who can withdraw funds? / யார் பணம் எடுக்கலாம்?",
  "තනිවම (ගිණුම්හිමියා / භාරකරු විසින් පමණි)": "Single (Account Holder/Guardian Only) / தனி (கணக்குதாரர்/பாதுகாவலர் மட்டும்)",
  "අපෙන් එක්කෙනෙකු (Anyone)": "Anyone / எவரேனும் ஒருவர்",
  "අප (සියලු දෙනාම එක්ව අත්සන් තබා)": "All Jointly / அனைவரும் கூட்டாக",
  "අපෙන් තිදෙනෙකු (All Three Signatures)": "All Three Signatures / மூவரின் கையொப்பங்கள்",
  "* අපෙන් කවරෙකු වුවද මිය ගිය විට ඒ මියගිය තැනැත්තාගේ නියෝජිතයන්ගෙන් කරුණු නොවිමසා ගිණුමෙහි ශේෂව ඇති මුදල ජීවත්ව සිටින අයට ගෙවීමට මෙයින් එකඟ වේ.": "* We agree that in the event of death of any of us, the balance will be paid to the survivor(s). / * எங்களில் எவரேனும் இறந்தால், நிலுவைத்தொகை உயிருடன் இருப்பவர்களுக்கு வழங்கப்படும் என ஒப்புக்கொள்கிறோம்.",
  "සාක්ෂිකරුගේ විස්තර (Witness)": "Witness Details / சாட்சி விவரங்கள்",
  "සාක්ෂිකරුගේ නම": "Witness Name / சாட்சியின் பெயர்",
  "ලිපිනය (හෝ සාමාජික අංකය)": "Address (or Member No) / முகவரி (அல்லது உறுப்பினர் எண்)",
  "* (සාමදාන විනිශ්චයකාර / ශ්‍රේෂ්ඨාධිකරණයේ පෙරකදෝරු / ප්‍රසිද්ධ නොතාරිස් හෝ සමිතියේ සාමාජිකයෙක් විය යුතුය)": "* (Must be a JP/Lawyer/Notary or Society Member) / * (சமாதான நீதவான்/வழக்கறிஞர்/நொத்தாரிசு அல்லது சங்க உறுப்பினராக இருக்க வேண்டும்)",
  "අයදුම්කරුගේ අත්සන (Specimen Signature)": "Specimen Signature / மாதிரி கையொப்பம்",
  "ස්කෑන් (Scan)": "Scan / ஸ்கேன்",
  "පින්තූරයක් (Upload)": "Upload / பதிவேற்று",
  "වර්තමාන ශේෂය (Current Available Balance - LKR)": "Current Available Balance - LKR / தற்போதைய நிலுவை - LKR",
  "ප්‍රථම තැන්පතු මුදල (Initial Deposit - LKR)": "Initial Deposit - LKR / ஆரம்ப வைப்பு - LKR",
  "* පැරණි ගිණුමේ අද දිනට පවතින සම්පූර්ණ ශේෂය මෙහි ඇතුළත් කරන්න.": "* Enter the total balance of the old account as of today. / * பழைய கணக்கின் இன்றைய நிலுவையை உள்ளிடுக.",
  "ඉතුරුම් ගිණුම් වර්ගය (Savings Account Type)": "Savings Account Type / சேமிப்பு கணக்கு வகை",
  "සාමාන්‍ය ඉතුරුම් (Normal Savings)": "Normal Savings / சாதாரண சேமிப்பு",
  "ජනසෙත (Janasetha)": "Janasetha / ஜனசெத",
  "ධන යෝජනා (Dhana Yojana)": "Dhana Yojana / தன யோஜனா",
  "වන්දනා (Vandana)": "Vandana / வந்தனா",
  "අරුණලු (Arunalu Minor Savings)": "Arunalu Minor Savings / அருணலு சிறுவர் சேமிப்பு",
  "රන්තිලින (Ranthilina Minor Savings)": "Ranthilina Minor Savings / ரந்திலின சிறுவர் சேமிப்பு",
  "සාර්ථකයි (Success)": "Success / வெற்றி",
  "අවධානයට (Attention)": "Attention / கவனம்",
  "හරි (OK)": "OK / சரி",
  "කරුණාකර ඉහළින් ඇති සෙවුම භාවිතයෙන් සාමාජිකයෙකු තෝරන්න (Please search and select a member first).": "Please search and select a member first. / தயவுசெய்து மேலே உள்ள தேடலைப் பயன்படுத்தி உறுப்பினரைத் தேர்ந்தெடுக்கவும்.",
  "කරුණාකර පළමුව අයදුම්කරු තෝරන්න (Please search and select the applicant first).": "Please search and select the applicant first. / தயவுசெய்து முதலில் விண்ணப்பதாரரைத் தேர்ந்தெடுக்கவும்.",
  "ගිණුම සාර්ථකව පද්ධතියට ඇතුළත් කරන ලදී! ගිණුම් අංකය:": "Account successfully added to the system! Account Number: / கணக்கு வெற்றிகரமாக அமைப்பில் சேர்க்கப்பட்டது! கணக்கு எண்:",
  "ගිණුම් වර්ගය (Scheme):": "Account Scheme: / கணக்கு வகை (Scheme):",
  "ගිණුම විවෘත කිරීමේදී දෝෂයක් මතු විය (Error creating account): ": "Error creating account: / கணக்கைத் திறப்பதில் பிழை:",
  "මුළු ගිණුම්": "Total Accounts / மொத்த கணக்குகள்",
  "සක්‍රිය ගිණුම්": "Active Accounts / செயலிலுள்ள கணக்குகள்",
  "අක්‍රිය ගිණුම්": "Inactive Accounts / செயலற்ற கணக்குகள்",
  "Deposit": "Deposit / வைப்பு",
  "Withdraw": "Withdraw / மீளப்பெறுக",
  "Open Account": "Open Account / கணக்கு ஆரம்பிக்கவும்",
  "සමාජීය": "Society / சங்கம்",
  "සමාජීය නොවන": "Non-Society / சங்கம் அல்லாத",
  "Search account number...": "Search account number... / கணக்கு எண்ணைத் தேடுக...",
  "ස්ථාවර තැන්පතු (Fixed Deposits)": "நிலையான வைப்புகள்",
  "කාලීන තැන්පතු කළමනාකරණය": "நிலையான வைப்பு முகாமைத்துவம்",
  "නව ගිණුමක් අරඹන්න": "புதிய கணக்கை ஆரம்பிக்கவும்",
  "සියලු ගිණුම්": "அனைத்து கணக்குகள்",
  "සක්‍රීය ගිණුම්": "செயலிலுள்ள கணக்குகள்",
  "දැනට ක්‍රියාකාරී": "தற்போது செயலில் உள்ளது",
  "තැන්පතු මුදල": "வைப்புத் தொகை",
  "සියලු තැන්පතු එකතුව": "அனைத்து வைப்புகளின் மொத்தம்",
  "කල් පිරීමට නියමිත": "முதிர்வடைய உள்ளது",
  "දින 30 ඇතුලත": "30 நாட்களுக்குள்",
  "කල් පිරුණු": "முதிர்வடைந்தவை",
  "වසා දැමූ": "மூடப்பட்டவை",
  "වසා දැමූ ගිණුම්": "மூடப்பட்ட கணக்குகள்",
  "ගිණුම් අංකය හො නම සොයන්න...": "கணக்கு எண் அல்லது பெயரைத் தேடுக...",
  "වර්ගය:": "வகை:",
  "සියල්ල": "அனைத்தும்",
  "සාමාන්‍ය ස්ථාවර තැන්පතු": "சாதாரண நிலையான வைப்புகள் (Normal Fixed Deposits)",
  "ජ්‍යෙෂ්ඨ පුරවැසි තැන්පතු": "சிரேஷ்ட பிரஜை வைப்புகள் (Senior Citizen Deposits)",
  "ළමා ස්ථාවර තැන්පතු": "சிறுவர் நிலையான வைப்புகள் (Minor Fixed Deposits)",
  "වර්තමාන තත්වය:": "தற்போதைய நிலை:",
  "ක්‍රියාත්මක": "செயலில்",
  "වසා ඇති / නිදහස් කළ": "மூடப்பட்ட / விடுவிக்கப்பட்ட",
  "පෙන්වන්නේ": "காண்பிக்கப்படுவது ",
  "ගිණුම්": "கணக்குகள்",
  "අංකය": "எண்",
  "තැන්පත්කරු": "வைப்பாளர்",
  "වර්ගය": "வகை",
  "තැන්පතු මුදල (Rs.)": "வைப்புத் தொகை (Rs.)",
  "කාලය /": "காலம் /",
  "පොළිය": "வட்டி",
  "කල් පිරීමේ දිනය": "முதிர்வுத் திகதி",
  "තත්ත්වය": "நிலை",
  "ක්‍රියාකාරකම්": "செயற்பாடுகள்",
  "මාස": "மாதங்கள்",
  "දින": "நாட்கள்",
  "කින් කල්පිරේ": "இல் முதிர்வடையும்",
  "බලන්න": "பார்க்க",
  "ක්‍රියාකාරී": "செயலில்",
  "කල් පිරීමට ආසන්නයි": "முதிர்வடைய உள்ளது",
  "අක්‍රියයි": "செயலற்றது",
  "වසා ඇත": "மூடப்பட்டது",
  "කල් පිරී ඇත": "முதிர்வடைந்தது",
  "සාමාන්‍ය": "சாதாரண",
  "ජ්‍යෙෂ්ඨ": "சிரேஷ்ட",
  "ළමා": "சிறுவர்",
  "පොදු ප්‍රමාදී": "பொது",
  "කොටස්මුදල්": "பங்குத் தொகை",
  "ණය ගිණුම් (Loan Accounts)": "கடன் கணக்குகள் (Loan Accounts)",
  "ණය කළමනාකරණය (Loan Management)": "கடன் மேலாண்மை (Loan Management)",
  "නව ණයක් ඉල්ලුම් කරන්න": "புதிய கடனைக் கோரவும்",
  "සියලු ණය ගිණුම්": "அனைத்து கடன் கணக்குகள்",
  "මුළු ණය මුදල": "மொத்த கடன் தொகை",
  "ඉල්ලුම් කළ ණය එකතුව": "கோரப்பட்ட கடன் மொத்தம்",
  "කමිටුව අනුමත කළ": "குழு அங்கீகரித்தது",
  "අනුමත වූ ණය": "அங்கீகரிக்கப்பட்ட கடன்கள்",
  "සක්‍රීය ණය": "செயலிலுள்ள கடன்கள்",
  "දැනට ගෙවන ණය": "தற்போது செலுத்தும் கடன்கள்",
  "ඉල්ලුම්පත් / ගිණුම් අංකය, සාමාජිකයා හෝ වර්ගය සොයන්න...": "விண்ணப்பம் / கணக்கு எண், உறுப்பினர் அல்லது வகையைத் தேடுக...",
  "සියලුම ණය": "அனைத்து கடன்கள்",
  "අනුමැතිය ලැබිය යුතු ණය": "அனுமதி பெற வேண்டிய கடன்கள்",
  "කල්පසු වූ ණය": "காலதாமதமான கடன்கள்",
  "අවසන් කළ ණය": "முடிக்கப்பட்ட கடன்கள்",
  "සියලුම ණය වර්ග": "அனைத்து கடன் வகைகள்",
  "සාමාජිකයා": "உறுப்பினர்",
  "ණය වර්ගය": "கடன் வகை",
  "මුදල (Rs.)": "தொகை (Rs.)",
  "ගෙවීමට ඇති මුදල": "செலுத்த வேண்டிய தொகை",
  "ක්‍රියා": "செயல்கள்",
  "ණය ගිණුම් කිසිවක් හමු නොවීය": "கடன் கணக்குகள் எதுவும் கிடைக்கவில்லை",
  "විනිශ්චය වෙමින් පවතී": "பரிசீலனையில் உள்ளது",
  "අනුමතයි": "அங்கீகரிக்கப்பட்டது",
  "ප්‍රතික්ෂේපිතයි": "நிராகரிக்கப்பட்டது",
  "මුදා හැර ඇත": "வழங்கப்பட்டது",
  "සක්‍රීයයි": "செயலிலுள்ளது",
  "සම්පූර්ණයි": "முடிக்கப்பட்டது",
  "මුදා හරින්න": "பட்டுவாடா செய்யவும்",
  "ලිපිය": "கடிதம்",
  "මකා දමන්න": "அழிக்கவும்",
  "උකස් ගිණුම් (Pawning Accounts)": "அடகு கணக்குகள் (Pawning Accounts)",
  "උකස් කළමනාකරණය (Pawning Management)": "அடகு மேலாண்மை (Pawning Management)",
  "වාරික ගෙවීම": "தவணை செலுத்துதல்",
  "නව උකස් පත්‍රිකාවක් නිකුත් කිරීම": "புதிய அடகு சீட்டு",
  "අනුමැතිය ලැබිය යුතු": "அனுமதி பெற வேண்டியவை",
  "අනුමැතිය සඳහා": "அனுமதிக்காக",
  "නිකුත් කළ යුතු": "வழங்க வேண்டியவை",
  "අනුමත කර ඇත": "அங்கீகரிக்கப்பட்டுள்ளது",
  "ක්‍රියාකාරී උකස්": "செயலிலுள்ள அடகுகள்",
  "කල් පිරීමට ආසන්න": "முதிர்ச்சியடைய உள்ளவை",
  "දින 30 ඇතුළත": "30 நாட்களுக்குள்",
  "අක්‍රිය උකස්": "செயலற்ற அடகுகள்",
  "කල් ඉකුත් වූ": "காலாவதியானவை",
  "නිදහස් කළ": "விடுவிக்கப்பட்டவை",
  "බේරාගත් උකස්": "மீட்கப்பட்ட அடகுகள்",
  "ටිකට් අංකය, සාමාජික අංකය, ජා.හැ.ප හෝ නම සොයන්න...": "சீட்டு எண், உறுப்பினர் எண், அ.அ.அ அல்லது பெயரைத் தேடுக...",
  "ටිකට්": "சீட்டு",
  "නම": "பெயர்",
  "නිකුත් කළ": "வழங்கப்பட்ட",
  "දිනය": "தேதி",
  "භාණ්ඩ": "பொருள்",
  "විස්තරය": "விவரம்",
  "උකස්": "அடகு",
  "අත්තිකාරම": "முன்பணம்",
  "කල් ඉකුත් වන": "காலாவதியாகும்",
  "ක්‍රියාව": "செயல்",
  "උකස් ගිණුම් නොමැත. (No pawning tickets found)": "அடகு கணக்குகள் எதுவும் கிடைக்கவில்லை",
  "අනුමැතියට යවා ඇත": "அனுமதிக்காக அனுப்பப்பட்டுள்ளது",
  "මුදල් නිකුත් කරන්න": "பணத்தை வழங்கவும்",
  "විවිධ සේවා සමුපකාර සමිතිය": "Multi-Purpose Cooperative Society / பல்நோக்கு கூட்டுறவு சங்கம்",
  "ස්ථාවර තැන්පතු ගිණුම් පෝරමය": "Fixed Deposit Account Form / நிலையான வைப்பு கணக்கு படிவம்",
  "ස්ථාවර තැන්පතු": "நிலையான வைப்பு (Fixed Deposit)",
  "නව ස්ථාවර තැන්පතු ගිණුමක් ආරම්භ කිරීම": "Open new fixed deposit account / புதிய நிலையான வைப்பு கணக்கை திறக்கவும்",
  "1. සාමාජික විස්තර (Member Details)": "1. Member Details / 1. உறுப்பினர் விவரங்கள்",
  "ගිණුම ආරම්භ කළ දිනය (OPENED DATE) *": "Opened Date / திறக்கப்பட்ட தேதி *",
  "තැන්පතු කාණ්ඩය (CATEGORY) *": "Category / வகை *",
  "-- තෝරන්න --": "-- Select / தேர்ந்தெடுக்கவும் --",
  "කාලය (TERM) *": "Term / காலம் *",
  "ගිණුම් වර්ගය (ACCOUNT TYPE) *": "Account Type / கணக்கு வகை *",
  "තනි ගිණුමක් (Individual)": "Individual / தனிநபர் கணக்கு",
  "හවුල් ගිණුමක් (Joint)": "Joint / கூட்டுக் கணக்கு",
  "සාමාජිකයා සොයන්න (SEARCH MEMBER)": "Search Member / உறுப்பினரை தேடுக",
  "NIC අංකය හෝ නම ටයිප් කරන්න...": "Type NIC or Name / தேசிய அடையாள அட்டை அல்லது பெயரை தட்டச்சு செய்க...",
  "අවලංගු කරන්න (Cancel)": "Cancel / ரத்து செய்",
  "ඊළඟ (Next)": "Next / அடுத்தது",
  "2. තැන්පතු තොරතුරු (Deposit Details)": "2. Deposit Details / 2. வைப்பு விவரங்கள்",
  "ස්ථාවර තැන්පතු අංකය (FD Number) *": "FD Number / நிலையான வைப்பு எண் *",
  "තැන්පතු මුදල (Principal Amount) *": "Principal Amount / அசல் தொகை *",
  "පොළිය ලබාගන්නා ක්‍රමය (Interest Payout) *": "Interest Payout / வட்டி செலுத்துதல் *",
  "කල් පිරුණම එකවර ගැනීම (At Maturity - Higher Rate)": "At Maturity (Higher Rate) / முதிர்வின் போது (அதிக வட்டி)",
  "මාසිකව ගැනීම (Monthly - Rate -2%)": "Monthly (Rate -2%) / மாதாந்திரம் (-2% வட்டி)",
  "කල් පිරීමේ උපදෙස් (Maturity Instructions) *": "Maturity Instructions / முதிர்வுக்கான அறிவுறுத்தல்கள் *",
  "1. මුල් මුදල සහ පොළිය නැවත ආයෝජනය කිරීම (Reinvest Principal & Interest)": "1. Reinvest Principal & Interest / 1. அசல் மற்றும் வட்டியை மீண்டும் முதலீடு செய்க",
  "2. මුල් මුදල නැවත ආයෝජනය කර, පොළිය ඉතුරුම් ගිණුමට (Reinvest Principal, Pay Interest)": "2. Reinvest Principal, Pay Interest / 2. அசலை முதலீடு செய்து, வட்டியை சேமிப்புக் கணக்கில் செலுத்துக",
  "3. ගිණුම වසා සියලු මුදල් ඉතුරුම් ගිණුමට (Close Account)": "3. Close Account / 3. கணக்கை மூடி எல்லாப் பணத்தையும் சேமிப்புக் கணக்கிற்கு மாற்றுக",
  "කරුණාකර අනුමත නිලධාරි ලෙස තහවුරු කරන්න (Please approve as authorized officer).": "Please approve as authorized officer / தயவுசெய்து அங்கீகரிக்கப்பட்ட அதிகாரியாக அங்கீகரிக்கவும்.",
  "3. කාර්යාලීය ප්‍රයෝජනය සඳහා පමණි (Office Use Only)": "3. Office Use Only / 3. அலுவலக பயன்பாட்டிற்கு மட்டும்",
  "කුවිතාන්සි අංකය (RECEIPT NO)": "Receipt No / ரசீது எண்",
  "තැන්පත්කරුගේ අත්සන (DEPOSITOR SIGNATURE)": "Depositor Signature / வைப்பாளர் கையொப்பம்",
  "තැන්පත් කළ දිනය (DEPOSIT DATE)": "Deposit Date / வைப்புத் தேதி",
  "කල්පිරෙන දිනය (MATURITY DATE)": "Maturity Date / முதிர்வுத் தேதி",
  "පොළී අනුපාතිකය (INTEREST RATE)": "Interest Rate / வட்டி விகிதம்",
  "බදු ආකෘති පත්‍රය ලබා දී ඇත (Tax form submitted)": "Tax form submitted / வரிப் படிவம் சமர்ப்பிக்கப்பட்டுள்ளது",
  "අනුමත කළ බලයලත් නිලධාරි අත්සන (Authorized Officer Approved)": "Authorized Officer Approved / அங்கீகரிக்கப்பட்ட அதிகாரி ஒப்புதல் அளித்துள்ளார்",
  "පෙර (Back)": "Back / முந்தைய",
  "තැන්පතුව ආරම්භ කරන්න (Open FD)": "Open FD / நிலையான வைப்பை திறக்கவும்",
  "කෙටි ණය": "Short Loan / குறுகிய கால கடன்",
  "සේවක ණය": "Staff Loan / பணியாளர் கடன்",
  "ක්ෂණික ණය": "Instant Loan / உடனடி கடன்",
  "ආපදා ණය": "Disaster Loan / அனர்த்தக் கடன்",
  "FD ණය (ස්ථාවර තැන්පතු ණය)": "FD Loan / நிலையான வைப்பு கடன்",
  "අර්ථ සාධක ණය": "EPF Loan / ஊழியர் சேமலாப நிதியக் கடன்",
  "දුරකථන ණය": "Phone Loan / தொலைபேசி கடன்",
  "මහා සභා ණය": "General Assembly Loan / பொதுச் சபை கடன்",
  "MPCS ණය (විවිධ සේවා සමුපකාර සමිති ණය)": "MPCS Loan / பல்நோக்கு கூட்டுறவு சங்க கடன்",
  "කොටස් ණය": "Share Loan / பங்கு கடன்",
  "කල්පසු ණය": "Overdue Loan / காலாவதியான கடன்",
  "සමිතියේ කල්පසු ණය": "Society Overdue Loan / சங்கத்தின் காலாவதியான கடன்",
  "පාරිභෝගික ණය": "Consumer Loan / நுகர்வோர் கடன்",
  "අත්තිකාරම් ණය": "Advance Loan / முன்பணக் கடன்",
  "Select a loan type to proceed with your application": "Select a loan type / கடன் வகையைத் தேர்ந்தெடுக்கவும்",
  "Max Amount": "Max Amount / அதிகபட்ச தொகை",
  "ණය වර්ග පූරණය වෙමින් පවතී... (Loading...)": "Loading... / ஏற்றப்படுகிறது...",
  "ණය වර්ග පූරණය කිරීම අසාර්ථක විය.": "Failed to load loan types / கடன் வகைகளை ஏற்ற முடியவில்லை.",
  "කිසිදු ණය වර්ගයක් සොයාගත නොහැකි විය.": "No loan types found / எந்த கடன் வகையும் கிடைக்கவில்லை.",
  "සී/ස විවිධ සේවා සමුපකාර සමිතිය | ග්රාමීය බැංකුව": "MPCS | Rural Bank / பல்நோக்கு கூட்டுறவு சங்கம் | கிராமிய வங்கி",
  "ණය යෝජනා ඉල්ලුම් පත්රය": "Loan Proposal Application / கடன் முன்மொழிவு விண்ணப்பம்",
  "අයදුම්පත් අංකය (Application No)": "Application No / விண்ணப்ப எண்",
  "ගිණුම ආරම්භ කළ දිනය / අයදුම් කළ දිනය (Applied Date)": "Applied Date / விண்ணப்பித்த தேதி",
  "ඔබ තෝරාගෙන ඇත්තේ අතීත දිනයකි. මෙය පැරණි දත්ත ඇතුලත් කිරීමක් බව තහවුරු කරගන්න.": "You have selected a past date. Confirm this is an old data entry. / நீங்கள் கடந்த தேதியைத் தேர்ந்தெடுத்துள்ளீர்கள். இது பழைய தரவு உள்ளீடு என்பதை உறுதிப்படுத்தவும்.",
  "01. ඉල්ලුම්කරුගේ මූලික තොරතුරු": "01. Applicant's Basic Details / 01. விண்ணப்பதாரரின் அடிப்படை விவரங்கள்",
  "සාමාජික අංකය, ජා.හැ.ප අංකය හෝ නම (Member No, NIC or Name) ලබා දී සොයන්න": "Search by Member No, NIC or Name / உறுப்பினர் எண், தே.அ.அ அல்லது பெயரைத் தேடுக",
  "සාමාජිකයෙකු සොයාගත නොහැකි විය. (Member not found)": "Member not found / உறுப்பினர் கிடைக்கவில்லை",
  "01. ඉල්ලුම්කරුගේ සම්පූර්ණ නම / නම්": "01. Applicant's Full Name / 01. விண்ணப்பதாரரின் முழுப் பெயர்",
  "02. ලිපිනය": "02. Address / 02. முகவரி",
  "03. උපන් දිනය": "03. Date of Birth / 03. பிறந்த தேதி",
  "04. ස්ත්රී / පුරුෂ භාවය": "04. Gender / 04. பாலினம்",
  "තෝරන්න": "Select / தேர்ந்தெடுக்கவும்",
  "පුරුෂ": "Male / ஆண்",
  "ස්ත්රී": "Female / பெண்",
  "05. විවාහක / අවිවාහක බව": "05. Marital Status / 05. திருமண நிலை",
  "විවාහක": "Married / திருமணமானவர்",
  "අවිවාහක": "Unmarried / திருமணமாகாதவர்",
  "06. ජාතික හැඳුනුම්පත් අංකය (NIC)": "06. NIC / 06. தேசிய அடையாள அட்டை (NIC)",
  "07. දුරකථන අංකය": "07. Phone Number / 07. தொலைபேசி எண்",
  "08. සාමාජික අංකය": "08. Member No / 08. உறுப்பினர் எண்",
  "09. සමිති බල ප්රදේශයේ පදිංචි කාලය (වසර)": "09. Period of Residence (Years) / 09. வசிக்கும் காலம் (ஆண்டுகள்)",
  "10. වෙනත් සමූපකාර සමිතියක සාමාජිකයෙක්ද?": "10. Member of another Coop Society? / 10. வேறு கூட்டுறவு சங்கத்தில் உறுப்பினரா?",
  "ඔව්": "Yes / ஆம்",
  "නැත": "No / இல்லை",
  "එසේ නම් එහි නම සහ ලිපිනය": "If yes, name and address / ஆம் எனில், அதன் பெயர் மற்றும் முகவரி",
  "02. ණය මුදල සහ ආර්ථික තොරතුරු": "02. Loan Amount and Economic Details / 02. கடன் தொகை மற்றும் பொருளாதார விவரங்கள்",
  "11. වෙනත් ණය වෙනුවෙන් ඇපවීම් (ඇත්නම් ණයකරුගේ නම)": "11. Guarantor for other loans (Debtor name) / 11. பிற கடன்களுக்கான உத்தரவாதம்",
  "ණයකරු 01 නම": "Debtor 01 Name / கடனாளி 01 பெயர்",
  "ණයකරු 02 නම": "Debtor 02 Name / கடனாளி 02 பெயர்",
  "12. ණය මුදල සහ ගෙවීමේ කාලය": "12. Loan Amount and Repayment Period / 12. கடன் தொகை மற்றும் திருப்பிச் செலுத்தும் காலம்",
  "(අ) අවශ්‍ය ණය මුදලින් (රු.)": "(a) Required Loan Amount (Rs.) / (அ) தேவையான கடன் தொகை (ரூ.)",
  "(ආ) අවශ්‍ය ණය ද්‍රව්‍ය වලින් (රු.)": "(b) Required Loan in Goods (Rs.) / (ஆ) பொருட்களாக தேவையான கடன் (ரூ.)",
  "එකතුව (Total Loan Amount)": "Total Loan Amount / மொத்த கடன் தொகை",
  "14. ණය ආපසු ගෙවීමේ කාලය": "14. Repayment Period / 14. திருப்பிச் செலுத்தும் காலம்",
  "(මාසික වාරික සංඛ්‍යාව)": "(Number of Monthly Installments) / (மாதாந்திர தவணைகளின் எண்ணிக்கை)",
  "13. ණය අවශ්‍ය කාරණය": "13. Purpose of Loan / 13. கடனுக்கான நோக்கம்",
  "උදා: ව්‍යාපාරයක් ආරම්භ කිරීමට": "e.g., Start a business / உ-ம்: ஒரு தொழிலைத் தொடங்க",
  "15. වාරික ගෙවීමේ ක්‍රමය": "15. Repayment Method / 15. தவணை செலுத்தும் முறை",
  "ක්ෂේත්‍ර නිලධාරී හරහා නිවසට පැමිණ": "Field Collection (Home) / கள அதிகாரி மூலம்",
  "ශාඛාවට පැමිණ (Branch Visit)": "Branch Visit / கிளைக்கு வருகை",
  "ණයකරුගේ ආර්ථික තොරතුරු": "Economic Details of Debtor / கடனாளியின் பொருளாதார விவரங்கள்",
  "01. ප්රධාන රැකියාව": "01. Primary Occupation / 01. பிரதான தொழில்",
  "02. රැකියාව කරන ආයතනයේ නම හා ලිපිනය": "02. Employer Name and Address / 02. தொழில் செய்யும் நிறுவனத்தின் பெயர், முகவரி",
  "03. බිරිඳ/ස්වාමිපුරුෂයා රැකියාවක් කරන්නේ නම් තනතුර": "03. Spouse's Job Title (if employed) / 03. கணவன்/மனைவி பணிபுரிந்தால் பதவி",
  "ආයතනයේ නම හා ලිපිනය (බිරිඳ/ස්වාමිපුරුෂයා)": "Spouse's Employer Name and Address / நிறுவனத்தின் பெயர் மற்றும் முகவரி (கணவன்/மனைவி)",
  "ගෘහ මූලිකයාගේ නම": "Head of Household Name / குடும்பத்தலைவரின் பெயர்",
  "යැපෙන්නන්ගේ සංඛ්යාව": "Number of Dependents / சார்ந்திருப்பவர்களின் எண்ணிக்கை",
  "03. වත්කම්, මූල්ය සහ වියදම් විස්තර": "03. Assets, Financial & Expense Details / 03. சொத்துக்கள், நிதி மற்றும் செலவு விவரங்கள்",
  "05. ස්ථිර වත්කම් (ණය ඉල්ලුම්කරු සතු ප්රමාණය හා වටිනාකම)": "05. Fixed Assets (Amount and Value) / 05. நிலையான சொத்துக்கள்",
  "ප්රමාණය සහ ඇස්තමේන්තුගත වටිනාකම": "Amount and Estimated Value / அளவு மற்றும் மதிப்பிடப்பட்ட மதிப்பு",
  "මූල්ය වත්කම් (බැංකු සහ ආයතන ගිණුම් විස්තර)": "Financial Assets (Bank Accounts) / நிதி சொத்துக்கள் (வங்கி கணக்கு விவரங்கள்)",
  "ගිණුම් වර්ගය": "Account Type / கணக்கு வகை",
  "ආයතනය": "Institution / நிறுவனம்",
  "ගිණුම් අංකය": "Account No / கணக்கு எண்",
  "ශේෂය (රු.)": "Balance (Rs.) / மீதி (ரூ.)",
  "වාර්ෂික ප්රධාන රැකියා ආදායම (රු.)": "Annual Primary Income (Rs.) / வருடாந்திர பிரதான வருமானம் (ரூ.)",
  "වෙනත් වාර්ෂික ආදායම් මාර්ග (රු.)": "Other Annual Income (Rs.) / பிற வருடாந்திர வருமானம் (ரூ.)",
  "මුළු වාර්ෂික වියදම් එකතුව (රු.)": "Total Annual Expenses (Rs.) / மொத்த வருடாந்திர செலவுகள் (ரூ.)",
  "07. දැනට ගෙවීමට ඇති ණය සහ පොළී විස්තර": "07. Current Outsatnding Loans & Interest / 07. தற்போது செலுத்த வேண்டிய கடன்கள் மற்றும் வட்டி விவரங்கள்",
  "1. මෙම සමිතියට ගෙවීමට ඇති හිඟ මුදල (රු.)": "1. Outstanding to this Society (Rs.) / 1. இந்த சங்கத்திற்கு செலுத்த வேண்டிய நிலுவை (ரூ.)",
  "2. වෙනත් මූල්ය ආයතනවලට ඇති ණය (රු.)": "2. Other Loans (Rs.) / 2. பிற நிறுவனங்களில் உள்ள கடன்கள் (ரூ.)",
  "08. අතිරේක ලියකියවිලි (Supporting Documents)": "08. Supporting Documents / 08. துணை ஆவணங்கள்",
  "ණය ඉල්ලුම්පත, වත්කම් ඔප්පු ආදියෙහි ස්කෑන් පිටපත් හෝ ඡායාරූප උඩුගත කරන්න": "Upload scanned copies of documents / ஆவணங்களின் ஸ்கேன் பிரதிகளை பதிவேற்றுக",
  "04. ඇපකරුවන්ගේ ප්රකාශ සහ විස්තර": "04. Guarantor Details / 04. பிணையாளர்களின் விவரங்கள்",
  "සම්පූර්ණ නම": "Full Name / முழுப் பெயர்",
  "ලිපිනය": "Address / முகவரி",
  "ජාතික හැඳුනුම්පත් අංකය": "NIC / தேசிய அடையாள அட்டை",
  "උපන් දිනය": "Date of Birth / பிறந்த தேதி",
  "සාමාජික අංකය": "Member No / உறுப்பினர் எண்",
  "රැකියාව": "Occupation / தொழில்",
  "දුරකථන අංකය": "Phone Number / தொலைபேசி எண்",
  "ඉඩම්/ගොඩනැගිලි වටිනාකම": "Land/Building Value / காணி/கட்டிட மதிப்பு",
  "රු.": "Rs. / ரூ.",
  "රථ වාහන වටිනාකම": "Vehicle Value / வாகன மதிப்பு",
  "ඉතිරි කිරීම් ශේෂය": "Savings Balance / சேமிப்பு மீதி",
  "වාර්ෂික මුළු ආදායම": "Total Annual Income / மொத்த வருடாந்திர வருமானம்",
  "ඇපකරුගේ ඩිජිටල් අත්සන (Digital Signature)": "Guarantor Digital Signature / பிணையாளரின் கையொப்பம்",
  "🔔 ඇපකරුවන් සහ ණයකරුගේ පොදු ප්රකාශය :": "🔔 Common Declaration : / 🔔 பொதுவான அறிவிப்பு :",
  "• ඉහත සඳහන් කරුණු අප දන්නා තරමින් නිවැරදි හා සත්ය බවත්, ණයකරු මෙම මුදල පැහැර හැරියහොත් පොළියද ඇතුළුව සම්පූර්ණ මුදල ගෙවීමට තනි තනිව සහ සාමූහිකව අප බැඳී සිටින බව ප්රකාශ කරමු.": "• We declare info is true & agree to pay total due if debtor defaults. / • தகவல்கள் உண்மையானவை மற்றும் கடனாளி தவறினால் செலுத்த ஒப்புக்கொள்கிறோம்.",
  "• වාරික මුදලක් නිසි පරිදි නොගෙවා හැරියහොත් සමිතියේ ඇති අපගේ ඕනෑම ගිණුම් ශේෂයක් හිලව් කර ගැනීමට අපගේ විරුද්ධත්වයක් නොමැත.": "• We agree to offset balances if installments are missed. / • தவணைகள் தவறினால் கணக்கு மீதியை கழிக்க சம்மதிக்கிறோம்.",
  "පෙර පියවර (Back)": "Back / முந்தைய படி",
  "මීළඟ පියවර (Next)": "Next / அடுத்த படி",
  "ශාඛා කළමනාකරුගේ අනුමැතිය සඳහා ඉදිරිපත් කරන්න (Submit for Approval)": "Submit for Approval / அனுமதிக்காக சமர்ப்பிக்கவும்",
  "සේවක ආපදා ණය ඉල්ලුම්පත": "Staff Disaster Loan Application / பணியாளர் அனர்த்த கடன் விண்ணப்பம்",
  "ගිණුම ආරම්භ කළ දිනය / අයදුම් කළ දිනය (Applied Date) *": "Applied Date * / விண்ணப்பித்த தேதி *",
  "1. අයදුම්කරුගේ තොරතුරු": "1. Applicant Info / 1. விண்ணப்பதாரரின் தகவல்",
  "1. නම": "1. Name / 1. பெயர்",
  "2. සාමාජික අංකය": "2. Member No / 2. உறுப்பினர் எண்",
  "කොටස් මුදල (රු.)": "Share Capital (Rs.) / பங்குத் தொகை (ரூ.)",
  "3. තනතුර": "3. Position / 3. பதவி",
  "4. ලිපිනය": "4. Address / 4. முகவரி",
  "2. ණය සහ ඇපකරුවන්ගේ විස්තර": "2. Loan & Guarantors Info / 2. கடன் மற்றும் பிணையாளர்கள் விவரம்",
  "5. ඉල්ලන ණය මුදල (රු.)": "5. Requested Amount (Rs.) / 5. கோரப்பட்ட கடன் தொகை (ரூ.)",
  "මාස ගණන (Term)": "Term (Months) / மாதங்களின் எண்ணிக்கை",
  "ඉහත සඳහන් මා හට මාසික වැටුපින් අයකර ගැනීමේ පදනම මත රුපියල්": "I request Rs. to be recovered from my monthly salary / எனது மாத சம்பளத்திலிருந்து கழிக்கப்படும் அடிப்படையில் ரூ.",
  "ආපදා ණය මුදලක් ලබාදෙන ලෙස ඉල්ලමි.": "as disaster loan. / அனர்த்தக் கடனாக வழங்கக் கோருகிறேன்.",
  "* ඉහත සඳහන් අයගේ ආපදා ණය මුදල සඳහා ඇපකරුවන් වශයෙන් බැඳීමට අප එකඟ වන බැව් ප්‍රකාශ කර සිටිමු.": "* We agree to stand as guarantors for this disaster loan. / * இக்கடனுக்காக பிணையாளர்களாக இருக்க நாங்கள் சம்மதிக்கிறோம்.",
  "6.1 පළමු ඇපකරු": "6.1 1st Guarantor / 6.1 முதல் பிணையாளர்",
  "නම": "Name / பெயர்",
  "සාර්ථකයි": "Success / வெற்றி",
  "6.2 දෙවන ඇපකරු": "6.2 2nd Guarantor / 6.2 இரண்டாம் பிணையாளர்",
  "අතිරේක ලියකියවිලි (Supporting Documents)": "Supporting Documents / துணை ஆவணங்கள்",
  "නව උකස් පත්‍රිකාවක් නිකුත් කිරීම (Issue New Pawn Ticket)": "Issue New Pawn Ticket / புதிய அடகு சீட்டை வழங்குதல்",
  "ගිණුම ආරම්භ කළ දිනය / නිකුත් කළ දිනය (Issue Date) *": "Issue Date * / வழங்கப்பட்ட தேதி *",
  "පරණ ගිණුම් සඳහා අදාළ දිනය තෝරන්න. (Select past date for historical records)": "Select past date for historical records / வரலாற்று பதிவுகளுக்கான கடந்த தேதியைத் தேர்ந்தெடுக்கவும்",
  "⚠️ පැරණි උකස් ඇතුළත් කිරීමක්": "⚠️ Old Pawn Entry / ⚠️ பழைய அடகு பதிவு",
  "සාමාජිකයා තෝරන්න (Select Member)": "Select Member / உறுப்பினரைத் தேர்ந்தெடுக்கவும்",
  "NIC හෝ නම මඟින් සොයන්න...": "Search by NIC or Name... / தேசிய அடையாள அட்டை அல்லது பெயர் மூலம் தேடுக...",
  "සාමාජිකයින් හමු නොවීය.": "Members not found. / உறுப்பினர்கள் கிடைக்கவில்லை.",
  "වාර්ෂික පොලිය": "Annual Interest Rate / வருடாந்திர வட்டி வீதம்",
  "උකස් පත්‍රිකා අංකය (Ticket Number) *": "Ticket Number * / அடகு சீட்டு எண் *",
  "භාණ්ඩ විස්තරය (Article Description) *": "Article Description * / பொருளின் விளக்கம் *",
  "දළ බර (Gross Weight - g) *": "Gross Weight (g) * / மொத்த எடை (g) *",
  "ශුද්ධ බර (Net Weight - g) *": "Net Weight (g) * / நிகர எடை (g) *",
  "රන් තත්වය (Purity - Karat) *": "Purity (Karat) * / தங்கத்தின் தூய்மை (கராட்) *",
  "අවලංගු කරන්න (Cancel)": "Cancel / ரத்துசெய்",
  "වාරික ගෙවීම (Payment)": "Installment Payment / தவணை செலுத்துதல்",
  "ගෙවන දිනය (Payment Date)": "Payment Date / செலுத்தும் தேதி",
  "* දිනය අනුව පොලිය ස්වයංක්‍රීයව වෙනස් වේ (අවසාන ගෙවීමේ සිට දින 15/30 ඛණ්ඩ අනුව).": "* Interest updates automatically by date (based on 15/30 day blocks). / * தேதி அடிப்படையில் வட்டி தானாக மாறும் (15/30 நாள் தொகுதிகள்).",
  "ඉතිරි මූලික මුදල (Principal)": "Remaining Principal / மீதமுள்ள அசல்",
  "මුළු ගෙවිය යුතු මුදල (Total Due)": "Total Due / செலுத்த வேண்டிய மொத்தம்",
  "ගෙවන මුදල (Payment Amount)": "Payment Amount / செலுத்தும் தொகை",
  "අවලංගු කරන්න": "Cancel / ரத்துசெய்",
  "පෙර ගෙවීම් වාර්තා (Payment History)": "Payment History / முந்தைய கொடுப்பனவு பதிவுகள்",
  "උකස් අත්තිකාරම් නිකුත් කිරීම": "Issue Pawn Advance / அடகு முன்பணத்தை வழங்குதல்",
  "සාමාජිකයා": "Member / உறுப்பினர்",
  "කළමනාකරු අනුමත කළ මුදල (Manager Approved)": "Manager Approved Amount / முகாமையாளர் அனுமதித்த தொகை",
  "කළමනාකරුගේ සටහන (Manager's Remarks)": "Manager's Remarks / முகாமையாளரின் குறிப்புகள்",
  "නිකුත් කරන උකස් අත්තිකාරම (Advance Amount) *": "Issued Advance Amount * / வழங்கப்படும் முன்பணம் *",
  "උදා: 50000.00": "e.g., 50000.00 / உ-ம்: 50000.00",
  "කළමනාකරු අනුමත කළ උපරිම අගය: Rs. ${Number(ticket.assessedValue).toLocaleString()}": "Manager approved max value: Rs. / முகாமையாளர் அனுமதித்த அதிகபட்ச மதிப்பு: ரூ.",
  "උකස් පත්‍රිකාව (Pawn Ticket)": "Pawn Ticket / அடகு சீட்டு",
  "විස්තර (Details)": "Details / விவரங்கள்",
  "කල් ඉකුත් වීමට ආසන්නයි! (Expiring Soon!)": "Expiring Soon! / விரைவில் காலாவதியாகிறது!",
  "මෙම උකස් පත්‍රිකාව දින 30ක් ඇතුළත කල් ඉකුත් වේ. කරුණාකර ගනුදෙනුකරු දැනුවත් කරන්න.": "This pawn ticket expires in 30 days. Please notify customer. / இந்த அடகு சீட்டு 30 நாட்களில் காலாவதியாகும். வாடிக்கையாளருக்கு அறிவிக்கவும்.",
  "සාමාජිකයා (Member)": "Member / உறுப்பினர்",
  "නිකුත් කළ දිනය / කල් ඉකුත් වන දිනය": "Issue Date / Expiry Date / வழங்கப்பட்ட தேதி / காலாவதி தேதி",
  "භාණ්ඩ විස්තරය (Article Description)": "Article Description / பொருளின் விளக்கம்",
  "දළ බර": "Gross Weight / மொத்த எடை",
  "ශුද්ධ බර": "Net Weight / நிகர எடை",
  "කැරට් අගය": "Karat Value / கராட் மதிப்பு",
  "මුල්‍ය විස්තර සහ ගණනය කිරීම් (Financial Details)": "Financial Details & Calculations / நிதி விவரங்கள் மற்றும் கணக்கீடுகள்",
  "තක්සේරු වටිනාකම (Assessed Value)": "Assessed Value / மதிப்பிடப்பட்ட மதிப்பு",
  "උකස් අත්තිකාරම (Advance Amount)": "Advance Amount / அடகு முன்பணம்",
  "ඉතිරි මූලික මුදල (Remaining Principal)": "Remaining Principal / மீதமுள்ள அசல்",
  "වාර්ෂික පොලිය (Interest Rate)": "Annual Interest Rate / வருடாந்திர வட்டி வீதம்",
  "ගත වූ දින ගණන (Days Elapsed)": "Days Elapsed / கடந்த நாட்கள்",
  "එකතු වූ පොලිය (Accrued Interest)": "Accrued Interest / சேர்ந்த வட்டி",
  "වත්මන් ඉතිරි මූලික මුදල (Remaining Principal)": "Current Remaining Principal / தற்போதைய மீதமுள்ள அசல்",
  "දිනය (Date)": "Date / தேதி",
  "ලදුපත් අංකය (Receipt No)": "Receipt No / பற்றுச்சீட்டு எண்",
  "මූලික මුදල (Principal)": "Principal / அசல் தொகை",
  "පොලිය (Interest)": "Interest / வட்டி",
  "මුළු ගෙවීම (Total Paid)": "Total Paid / மொத்த செலுத்துகை",
  "මෙම උකස් පත්‍රිකාව සඳහා තවමත් කිසිදු වාරික ගෙවීමක් සිදු කර නොමැත.": "No installment payments made yet for this pawn ticket. / இந்த அடகு சீட்டுக்கு இதுவரை எந்த தவணை கொடுப்பனவும் செய்யப்படவில்லை.",
  "විස්තරයක් දක්වා නැත.": "No description provided. / எந்த விளக்கமும் வழங்கப்படவில்லை.",
  "වාරික ගෙවීම (Pay Installment)": "Pay Installment / தவணை செலுத்துதல்",
  "උකස් ගිණුම් (Pawning Accounts)": "அடகு கணக்குகள்",
  "උකස් කළමනාකරණය (Pawning Management)": "அடகு முகாமைத்துவம்",
  "වාරික ගෙවීම": "தவணை செலுத்துதல்",
  "නව උකස් පත්‍රිකාවක් නිකුත් කිරීම": "புதிய அடகு சீட்டை வழங்குதல்",
  "මුළු ගිණුම්": "மொத்த கணக்குகள்",
  "සියලු ගිණුම්": "அனைத்து கணக்குகளும்",
  "අනුමැතිය ලැබිය යුතු": "அனுமதிக்காக காத்திருப்பவை",
  "අනුමැතිය සඳහා": "அனுமதிக்காக",
  "නිකුත් කළ යුතු": "வழங்கப்பட வேண்டியவை",
  "අනුමත කර ඇත": "அனுமதிக்கப்பட்டுள்ளது",
  "ක්‍රියාකාරී උකස්": "செயலில் உள்ள அடகுகள்",
  "සක්‍රිය ගිණුම්": "செயலில் உள்ள கணக்குகள்",
  "කල් පිරීමට ආසන්න": "முதிர்வடையும் தருவாயில்",
  "දින 30 ඇතුළත": "30 நாட்களுக்குள்",
  "අක්‍රිය උකස්": "செயலிழந்த அடகுகள்",
  "කල් ඉකුත් වූ": "காலாவதியானவை",
  "නිදහස් කළ": "விடுவிக்கப்பட்டவை",
  "බේරාගත් උකස්": "மீட்கப்பட்ட அடகுகள்",
  "ටිකට් අංකය, සාමාජික අංකය, ජා.හැ.ප හෝ නම සොයන්න...": "சீட்டு எண், உறுப்பினர் எண், தே.அ.அ அல்லது பெயரால் தேடுக...",
  "ටිකට්": "சீட்டு",
  "අංකය": "எண்",
  "සාමාජික": "உறுப்பினர்",
  "නම": "பெயர்",
  "නිකුත් කළ": "வழங்கப்பட்ட",
  "දිනය": "தேதி",
  "භාණ්ඩ": "பொருள்",
  "විස්තරය": "விளக்கம்",
  "උකස්": "அடகு",
  "අත්තිකාරම": "முன்பணம்",
  "කල් ඉකුත් වන": "காலாவதியாகும்",
  "තත්ත්වය": "நிலை",
  "ක්‍රියාව": "செயல்",
  "උකස් ගිණුම් නොමැත. (No pawning tickets found)": "அடகு சீட்டுகள் எதுவும் கிடைக்கவில்லை",
  "බලන්න": "பார்க்கவும்",
  "මුදල් නිකුත් කරන්න": "பணத்தை வழங்குக",
  "වාරික ගෙවීම (Installment Payment)": "தவணை செலுத்துதல்",
  "උකස් පත්‍රිකා අංකය ඇතුළත් කරන්න": "அடகு சீட்டு எண்ணை உள்ளிடுக",
  "උකස් පත්‍රිකා අංකය (Pawn Ticket Number) *": "Pawn Ticket Number * / அடகு சீட்டு எண் *",
  "අවලංගු කරන්න": "Cancel / ரத்துசெய்",
  "පිරික්සන්න (Proceed)": "தொடரவும்",
  "අනුමැතියට යවා ඇත": "அனுமதிக்காக அனுப்பப்பட்டுள்ளது",
  "ක්‍රියාකාරී": "செயலில்",
  "අක්‍රියයි": "செயலிழந்துள்ளது",
  "කල් පිරීමට ආසන්නයි": "முதிர்வடையும் தருவாயில்",
  "පෙර වාර්තා": "முந்தைய பதிவுகள்",
  "අනුමැතිය සඳහා පොරොත්තුවෙන් පවතින උකස් අයදුම්පත් නොමැත.": "அனுமதிக்காக காத்திருக்கும் அடகு விண்ணப்பங்கள் எதுவும் இல்லை.",
  "රක්ෂණ වාර්තාව (Insurance Report)": "காப்புறுதி அறிக்கை",
  "ණය මුදාහැරීම් සඳහා මාසික රක්ෂණ වාර්තාව": "கடன் வழங்குவதற்கான மாதாந்திர காப்புறுதி அறிக்கை",
  "මාසය (Month):": "மாதம் (Month):",
  "Download (.doc)": "பதிவிறக்குக (.doc)",
  "Loading data...": "தரவு ஏற்றப்படுகிறது...",
  "කිසිදු දත්තයක් හමු නොවීය": "எந்த தரவும் கிடைக்கவில்லை",
  "මාසය සඳහා මුදාහැර ඇති ණය නොමැත.": "மாதத்திற்கு வழங்கப்பட்ட கடன்கள் எதுவும் இல்லை.",
  "No": "எண்",
  "Member Full Name": "உறுப்பினரின் முழுப் பெயர்",
  "Loan Period": "கடன் காலம்",
  "Member Gender": "பாலினம்",
  "Member NIC No": "தே.அ.அட்டை எண்",
  "Life Cover": "ஆயுள் காப்புறுதி",
  "Premium": "காப்புறுதிக் கட்டணம்",
  "උපදෙස (Tip):": "உதவிக்குறிப்பு:",
  "Life Cover සහ Premium අගයන් හිස් කොටුවල (Input boxes) Type කරන්න. ඊටපස්සේ \"Download (.doc)\" බටන් එක එබුවම, ඔයා Type කරපු අගයන් සහ එකතුව (Total) එක්කම Report එක Word File එකක් විදිහට Download වෙයි.": "ஆயுள் காப்புறுதி மற்றும் காப்புறுதிக் கட்டண மதிப்புகளை தட்டச்சு செய்க. பின்னர் \"Download (.doc)\" பொத்தானை அழுத்தினால், நீங்கள் தட்டச்சு செய்த மதிப்புகள் மற்றும் மொத்தத்துடன் அறிக்கை Word கோப்பாக பதிவிறக்கப்படும்.",
  "මුළු සාමාජිකයින්": "மொத்த உறுப்பினர்கள்",
  "Total Accounts": "மொத்த கணக்குகள்",
  "සාමාජික නොවන අය": "உறுப்பினர் அல்லாதவர்கள்",
  "සාමාජිකයින් සහ ගනුදෙනුකරුවන්": "உறுப்பினர்கள் மற்றும் வாடிக்கையாளர்கள்",
  "ලියාපදිංචි කරන්න": "பதிவு செய்",
  "Search by name or NIC...": "பெயர் அல்லது தே.அ.அட்டை மூலம் தேடுக...",
  "සියල්ල": "அனைத்தும்",
  "සාමාජිකයින්": "உறுப்பினர்கள்",
  "All Ages": "அனைத்து வயதுகளும்",
  "Adults Only": "பெரியவர்கள் மட்டும்",
  "Children Only": "குழந்தைகள் மட்டும்",
  "සාමාජිකයා / ගනුදෙනුකරු": "உறுப்பினர் / வாடிக்கையாளர்",
  "සාමාජික / සේවාලාභී අංකය": "உறுப்பினர் / வாடிக்கையாளர் எண்",
  "NIC / Birth Cert. No.": "தே.அ.அட்டை / பிறப்புச் சான்றிதழ் எண்",
  "Accounts": "கணக்குகள்",
  "කිසිදු සාමාජිකයෙකු හෝ ගනුදෙනුකරුවෙකු හමු නොවීය.": "உறுப்பினர் அல்லது வாடிக்கையாளர் யாரும் காணப்படவில்லை.",
  "සාමාජික": "உறுப்பினர்",
  "සාමාජික නොවන": "உறுப்பினர் அல்லாதவர்",
  "View Accounts": "கணக்குகளைப் பார்க்கவும்",
  "Profile": "சுயவிவரம்",
  "Accounts for": "கணக்குகள்:",
  "Savings": "சேமிப்புகள் (Savings)",
  "Loans": "கடன்கள் (Loans)",
  "Pawning": "அடகு (Pawning)",
  "Product / Type": "உற்பத்தி / வகை (Product / Type)",
  "Current Rate": "தற்போதைய வீதம் (Current Rate)",
  "Actions": "செயல்கள் (Actions)",
  "Maturity Rate (කල් පිරුණම)": "முதிர்வு வீதம் (Maturity Rate)",
  "Monthly Rate (මාසිකව)": "மாதாந்திர வீதம் (Monthly Rate)",
  "(වා.පො.)": "ஆ.வ. (p.a.)",
  "ළමා": "சிறுவர் (Child)",
  "වැඩිහිටි": "பெரியவர் (Adult)",
  "ධන යෝජනා": "தன யோஜனா (Dhana Yojana)",
  "රන්කිලින": "ரன்கிலின (Rankilina)",
  "රන්තිලින": "ரந்திலின (Ranthilina)",
  "ජීවන": "ஜீவன (Jeevana)",
  "අරුණලු": "அருணலு (Arunalu)",
  "වන්දනා": "வந்தனா (Vandana)",
  "ජනසෙත": "ஜனசெத (Janasetha)",
  "සාමාන්‍ය": "சாதாரண (Normal)",
  "සුළු ණය": "சிறு கடன் (Petty Loan)",
  "සාමාන්‍ය ණය": "சாதாரண கடன் (Normal Loan)",
  "විශේෂ ණය": "விசேட கடன் (Special Loan)",
  "කෙටි කාලීන ණය": "குறுகிய கால கடன் (Short Term Loan)",
  "දේපළ ණය": "சொத்துக் கடன் (Property Loan)",
  "වාහන ණය": "வாகனக் கடன் (Vehicle Loan)",
  "ප්‍රාග්ධන ණය": "மூலதனக் கடன் (Capital Loan)",
  "No savings account types found.": "சேமிப்புக் கணக்கு வகைகள் எதுவும் காணப்படவில்லை (No savings account types found.)",
  "අවුරුදු": "வருடங்கள் (Years)",
  "Manager Operations": "முகாமையாளர் செயற்பாடுகள் (Manager Operations)",
  "කළමනාකාර අනුමැතිය": "முகாமையாளர் அனுமதி (Manager Approval)",
  "කමිටුව අනුමත කළ ණය": "குழு அங்கீகரித்த கடன்கள் (Committee Approved Loans)",
  "Pawning Approvals": "அடகு அங்கீகாரங்கள் (Pawning Approvals)",
  "Auditor Comments": "கணக்காய்வாளர் கருத்துகள் (Auditor Comments)",
  "Customer Relations": "வாடிக்கையாளர் உறவுகள் (Customer Relations)",
  "Core Banking Facilities": "முக்கிய வங்கி வசதிகள் (Core Banking Facilities)",
  "Pawning (Gold Loans)": "அடகு (Pawning)",
  "Daily Operations": "தினசரி செயற்பாடுகள் (Daily Operations)",
  "ක්ෂේත්‍ර නිලධාරී මුදල් භාරගැනීම්": "கள உத்தியோகத்தர் பணம் கையளிப்பு (Field Officer Handover)",
  "Summary Ledger": "சுருக்க பேரேடு (Summary Ledger)",
  "Cash Balances": "பண மீதிகள் (Cash Balances)",
  "Information": "தகவல் (Information)",
  "ශාඛා සාරාංශ ලේඛනය (Branch Summary Ledger)": "கிளை சுருக்க பேரேடு (Branch Summary Ledger)",
  "පෙරහන් කරන්න (Filter By):": "வடிகட்டுக (Filter By):",
  "මාසික (Monthly)": "மாதாந்திரம் (Monthly)",
  "කාලය (Period)": "காலம் (Period)",
  "මුද්‍රණය කරන්න (Print)": "அச்சிடுக (Print)",
  "දත්ත සාරාංශය සකස් කරමින්... (Generating ledger balances...)": "தரவு சுருக்கத்தை உருவாக்குகிறது... (Generating ledger balances...)",
  "දත්ත ලබා ගැනීමට අපොහොසත් විය.": "தரவைப் பெற முடியவில்லை. (Failed to fetch data.)",
  "ලේඛනය (Category)": "வகை (Category)",
  "ගි/ගණ": "கணக்குகள் (Count)",
  "ශේෂය (Balance)": "மீதி (Balance)",
  "ඉතුරුම් තැන්පතු (Savings Deposits)": "சேமிப்பு வைப்புகள் (Savings Deposits)",
  "සාමාජික ගිණුම් (Member Accounts)": "உறுப்பினர் கணக்குகள் (Member Accounts)",
  "සාමාජික නොවන ගිණුම් (Non-Member Accounts)": "உறுப்பினர் அல்லாத கணக்குகள் (Non-Member Accounts)",
  "සාමාජික අක්‍රීය ගිණුම් (Inactive Member Accounts)": "செயலற்ற உறுப்பினர் கணக்குகள் (Inactive Member Accounts)",
  "සාමාජික නොවන අක්‍රීය ගිණුම් (Inactive Non-Member Accounts)": "செயலற்ற உறுப்பினர் அல்லாத கணக்குகள் (Inactive Non-Member Accounts)",
  "එකතුව (සාමාජික ගිණුම්)": "மொத்தம் (உறுப்பினர் கணக்குகள்)",
  "එකතුව (සාමාජික නොවන ගිණුම්)": "மொத்தம் (உறுப்பினர் அல்லாத கணக்குகள்)",
  "එකතුව (සාමාජික අක්‍රීය)": "மொத்தம் (செயலற்ற உறுப்பினர் கணக்குகள்)",
  "එකතුව (සාමාජික නොවන අක්‍රීය)": "மொத்தம் (செயலற்ற உறுப்பினர் அல்லாத கணக்குகள்)",
  "එකතුව (ඉතුරුම් තැන්පතු)": "மொத்தம் (சேமிப்பு வைப்புகள்)",
  "ස්ථාවර තැන්පතු (Fixed Deposits)": "நிலையான வைப்புகள் (Fixed Deposits)",
  "එකතුව (ස්ථාවර තැන්පතු)": "மொத்தம் (நிலையான வைப்புகள்)",
  "ණය ගිණුම් (Loans & Advances)": "கடன் கணக்குகள் (Loans & Advances)",
  "එකතුව (ණය ගිණුම්)": "மொத்தம் (கடன் கணக்குகள்)",
  "උකස් අත්තිකාරම් (Pawn Advances)": "அடகு முற்பணங்கள் (Pawn Advances)",
  "එකතුව (උකස් අත්තිකාරම්)": "மொத்தம் (அடகு முற்பணங்கள்)",
  "ක්ෂණික ණය": "உடனடி கடன் (Instant Loan)",
  "කෙටි ණය": "குறுகிய கடன் (Short Loan)",
  "සේවක ණය": "ஊழியர் கடன் (Staff Loan)",
  "කල්පසු වූ ණය (Overdue Loans)": "காலங்கடந்த கடன்கள் (Overdue Loans)",
  "උ/ණය (Pawn Loans)": "அடகு கடன்கள் (Pawn Loans)",
  "උ/වාරික (Pawn Repayments)": "அடகு மீளளிப்புகள் (Pawn Repayments)",
  "ශාඛාව (Branch):": "கிளை (Branch):",
  "යලි ගොඩනැගීමේ ස්ථාවර තැන්පතු": "மறுசீரமைப்பு நிலையான வைப்புகள் (Reconstruction Fixed Deposits)",
  "යළි ගොඩනැගීමේ ස්ථාවර තැන්පතු": "மறுசீரமைப்பு நிலையான வைப்புகள் (Reconstruction Fixed Deposits)",
  "ජංගම සේවා ස්ථාවර තැන්පතු": "நடமாடும் சேவை நிலையான வைப்புகள் (Mobile Service Fixed Deposits)",
  "ජංගම සේවක ස්ථාවර තැන්පතු": "நடமாடும் ஊழியர் நிலையான வைப்புகள் (Mobile Staff Fixed Deposits)",
  "අරින සාදන ණය": "வீட்டு வசதி கடன் (Housing Loan)",
  "අළුත් සාදන ණය": "வீட்டு வசதி கடன் (Housing Loan)",
  "ගෘහ සාදන ණය": "வீட்டு வசதி கடன் (Housing Loan)",
  "අලුත් වැඩියා ණය": "திருத்த வேலை கடன் (Renovation Loan)",
  "ජනවාරි (January)": "ஜனவரி (January)",
  "පෙබරවාරි (February)": "பிப்ரவரி (February)",
  "මාර්තු (March)": "மார்ச் (March)",
  "අප්‍රේල් (April)": "ஏப்ரல் (April)",
  "මැයි (May)": "மே (May)",
  "ජූනි (June)": "ஜூன் (June)",
  "ජූලි (July)": "ஜூலை (July)",
  "අගෝස්තු (August)": "ஆகஸ்ட் (August)",
  "සැප්තැම්බර් (September)": "செப்டம்பர் (September)",
  "ඔක්තෝබර් (October)": "அக்டோபர் (October)",
  "නොවැම්බර් (November)": "நவம்பர் (November)",
  "දෙසැම්බර් (December)": "டிசம்பர் (December)",
  "පවරා ඇති ක්ෂේත්‍ර නිලධාරී මුදල් භාරගැනීම් (Field Officer Handovers)": "கள உத்தியோகத்தர் பணம் கையளிப்பு (Field Officer Handovers)",
  "දිනය (Date):": "தேதி (Date):",
  "මේ මොහොතේ ක්ෂේත්‍ර නිලධාරීන්ගෙන් භාරගැනීමට මුදල් නොමැත. (No pending handovers from field officers at this moment.)": "இந்த தருணத்தில் கள உத்தியோகத்தர்களிடமிருந்து பொறுப்பேற்க எந்த பணமும் இல்லை. (No pending handovers from field officers at this moment.)",
  "ණය අංකය (Loan No)": "கடன் எண் (LOAN NO)",
  "මුදල (Amount)": "தொகை (AMOUNT)",
  "ක්‍රියාව (Action)": "செயல் (ACTION)",
  "භාරගන්නා ලදී": "பொறுப்பேற்கப்பட்டது (Accepted)",
  "භාරගන්න": "பொறுப்பேற்க (Accept)",
  "සාමාජිකයා (Member)": "உறுப்பினர் (MEMBER)",
  "ලිපිනය (Address)": "முகவரி (ADDRESS)",
  "දිනය (Date)": "தேதி (DATE)",
  "ණය මුදල නිකුත් කිරීම": "கடன் வழங்கல் (Loan Disbursement)",
  "ණය වාරිකය අයකර ගැනීම": "கடன் தவணை அறவீடு (Loan Repayment)",
  "මුදල් තැන්පතුව": "பண வைப்பு (Cash Deposit)",
  "මුදල් ආපසු ගැනීම": "பண மீளப்பெறல் (Cash Withdrawal)",
  "උකස් අත්තිකාරම් නිකුතුව": "அடகு முற்பணம் வழங்கல் (Pawning Advance)",
  "උකස් බේරා ගැනීම": "அடகு மீட்டல் (Pawning Redemption)",
  "Fixed Deposit Open": "நிலையான வைப்பு ஆரம்பம் (Fixed Deposit Open)",
  "Pawning Repayment": "அடகு மீளளிப்பு (Pawning Repayment)",
  "Savings Deposit:": "சேமிப்பு வைப்பு (Savings Deposit):",
  "Savings Withdrawal:": "சேமிப்பு மீளப்பெறல் (Savings Withdrawal):",
  "ක්ෂේත්‍ර නිලධාරී අත්තිකාරම් බේරුම් කිරීම": "கள உத்தியோகத்தர் முற்பணத் தீர்வு (Field Officer Advance Settlement)",
  "හඳුනා නොගත් ගනුදෙනුවක් (Unknown Transaction)": "அடையாளம் காணப்படாத பரிவர்த்தனை (Unknown Transaction)",
  "සාමාජිකයා (Member):": "உறுப்பினர் (Member):",
  "ක්‍රමය (Method):": "முறை (Method):",
  "දිනය/වේලාව (Date/Time):": "தேதி/நேரம் (Date/Time):",
  "ණය වර්ගය (Loan Type):": "கடன் வகை (Loan Type):",
  "ලැබීම් නොමැත (No inflows)": "வரவுகள் இல்லை (No inflows)",
  "ගෙවීම් නොමැත (No outflows)": "கொடுப்பனவுகள் இல்லை (No outflows)",
  "ණය ඉල්ලීම් සමාලෝචනය | Loan Application Review": "கடன் விண்ணப்ப மீளாய்வு (LOAN APPLICATION REVIEW)",
  "① අයදුම්කරුගේ තොරතුරු": "① விண்ணப்பதாரரின் தகவல் (Applicant Information)",
  "සම්පූර්ණ නම": "முழுப் பெயர் (Full Name)",
  "ජා.හැ.ප. අංකය": "தே.அ.அ. எண் (NIC No)",
  "සාමාජික අංකය": "உறுப்பினர் எண் (Member No)",
  "ලිපිනය": "முகவரி (Address)",
  "ජංගම දූරකථනය": "கைபேசி (Mobile)",
  "ඉල්ලූ ණය මුදල": "கோரிய கடன் தொகை (Requested Amount)",
  "ණය අරමුණ": "கடன் நோக்கம் (Loan Purpose)",
  "ණය ගෙවීමේ කාලය": "கடன் செலுத்தும் காலம் (Loan Term)",
  "වාර්ෂික පොලී අනුපාතය": "ஆண்டு வட்டி வீதம் (Annual Interest Rate)",
  "ණය ප්‍රමාණය (ද්‍රව්‍ය)": "கடன் அளவு (பொருட்கள்) (Loan Amount - Goods)",
  "② වත්කම් විස්තර": "② சொத்து விவரங்கள் (Asset Details)",
  "ගොඩ ඉඩම": "மேட்டு நிலங்கள் (Highlands)",
  "මඩ ඉඩම": "வயல் நிலங்கள் (Mudlands)",
  "වාහන": "வாகனங்கள் (Vehicles)",
  "සතුන්": "மிருகங்கள் (Animals)",
  "වාර්ෂික ප්‍රාථමික ආදායම": "ஆண்டு அடிப்படை வருமானம் (Annual Primary Income)",
  "වාර්ෂික වියදම": "ஆண்டு செலவு (Annual Expense)",
  "③ ඇපකරුවන්ගේ විස්තර": "③ பிணையாளர் விவரங்கள் (Guarantor Details)",
  "නම": "பெயர் (Name)",
  "ඩිජිටල් අත්සන": "டிஜிட்டல் கையொப்பம் (Digital Signature)",
  "වසන්න (Close)": "மூடுக (Close)",
  "ප්‍රතික්ෂේප කරන්න (Reject)": "நிராகரிக்க (Reject)",
  "අනුමත කරන්න (Approve)": "அனுமதிக்க (Approve)",
  "අත්තිකාරම් ණය": "முற்பணக் கடன் (Advance Loan)",
  "මාස (Months)": "மாதங்கள்",
  "⑤ අදහස් / Comments": "⑤ கருத்துக்கள் (Comments)",
  "ඔබගේ අදහස් හෝ ප්‍රතික්ෂේප කිරීමේ හේතුව ලියන්න...": "உங்கள் கருத்துக்கள் அல்லது நிராகரிப்பதற்கான காரணத்தை எழுதவும்...",
  "ක්ෂේත්‍ර නිලධාරීවරයෙකුට පවරන්න (Assign to Field Officer)": "கள உத்தியோகத்தருக்கு நியமிக்க (Assign to Field Officer)",
  "-- නිලධාරියා තෝරන්න --": "-- உத்தியோகத்தரைத் தேர்ந்தெடுக்கவும் --",
  "පවරන්න (Assign)": "நியமிக்க (Assign)",
  "✓ දැනටමත් පවරා ඇත (Status: ": "✓ ஏற்கனவே நியமிக்கப்பட்டுள்ளது (Status: ",
  "✗ ප්‍රතික්ෂේප කරන්න (Reject)": "✗ நிராகரிக்க (Reject)",
  "✓ අනුමත කරන්න (Approve)": "✓ அனுமதிக்க (Approve)",
  "✓ අනුමත කරන්න (Approve)": "✓ அனுமதிக்க (Approve)",
  "ණය කමිටුවට වෙත යවන්න (Send to Loan Committee)": "கடன் குழுவிற்கு அனுப்பவும் (Send to Loan Committee)",
  "අනුමැතිය ලැබිය යුතු උකස් අයදුම්පත්": "அனுமதிக்க வேண்டிய அடகு விண்ணப்பங்கள் (Pending Pawning Applications)",
  "අනුමැතිය සඳහා පොරොත්තුවෙන් පවතින උකස් අයදුම්පත් නොමැත.": "அனுமதிக்க காத்திருக்கும் அடகு விண்ணப்பங்கள் எதுவும் இல்லை. (No pending pawning applications.)",
  "උකස් ඉල්ලුම්කරු": "அடகு விண்ணப்பதாரர் (Pawning Applicant)",
  "සාමාජික අංකය:": "உறுப்பினர் எண் (Member No):",
  "උකස් පත්‍රිකා අංකය:": "அடகு சீட்டு எண் (Pawning Ticket No):",
  "ශාඛාව:": "கிளை (Branch):",
  "දළ බර:": "மொத்த எடை (Gross Weight):",
  "පරීක්ෂා කර අනුමත කරන්න": "பரிசோதித்து அனுமதிக்க (Review & Approve)",
  "පෙර උකස් වාර්තා": "முந்தைய அடகு பதிவுகள் (Previous Pawning Records)",
  "පෙර උකස් වාර්තා නොමැත.": "முந்தைய அடகு பதிவுகள் எதுவும் இல்லை. (No previous pawning records.)",
  "අනුමත මුදල:": "அனுமதிக்கப்பட்ட தொகை (Approved Amount):",
  "අනුමතයි": "அனுமதிக்கப்பட்டது (Approved)",
  "Edit Profile": "சுயவிவரத்தை திருத்துக (Edit Profile)",
  "Register New Member": "புதிய உறுப்பினரை பதிவுசெய்க (Register New Member)",
  "Register Non-Member": "உறுப்பினர் அல்லாதவரை பதிவுசெய்க (Register Non-Member)",
  "Identification Details": "அடையாள விவரங்கள் / Identification Details",
  "Society Member": "சங்க உறுப்பினர் (Society Member)",
  "Non-Member": "உறுப்பினர் அல்லாதவர் (Non-Member)",
  "Age Category": "வயது வகை (Age Category)",
  "Adult (18+)": "பெரியவர் (Adult 18+)",
  "Child (Under 18)": "குழந்தை (Child Under 18)",
  "Membership Number": "உறுப்பினர் எண் / Membership Number",
  "Child ID": "குழந்தை ஐடி (Child ID)",
  "Client ID": "வாடிக்கையாளர் ஐடி (Client ID)",
  "Personal Information": "தனிப்பட்ட தகவல் / Personal Information",
  "Birth Certificate No.": "பிறப்புச் சான்றிதழ் எண் (Birth Certificate No.)",
  "National Identity Card (NIC)": "தேசிய அடையாள அட்டை / NIC",
  "Name with Initials": "முதலெழுத்துக்களுடன் பெயர் / Name with Initials",
  "Full Name (English)": "முழுப் பெயர் (ஆங்கிலத்தில்) / Full Name (English)",
  "Date of Birth": "பிறந்த தேதி (Date of Birth)",
  "Gender": "பாலினம் (Gender)",
  "Male": "ஆண் (Male)",
  "Female": "பெண் (Female)",
  "Marital Status": "திருமண நிலை (Marital Status)",
  "Unmarried": "திருமணமாகாதவர் (Unmarried)",
  "Married": "திருமணமானவர் (Married)",
  "Cancel": "ரத்துசெய் (Cancel)",
  "Address": "முகவரி (Address)",
  "Contact Number": "தொடர்பு எண் (Contact Number)",
  "Province": "மாகாணம் (Province)",
  "Membership Details": "உறுப்பினர் விவரங்கள் (Membership Details)",
  "Number of Shares": "பங்குகளின் எண்ணிக்கை (Number of Shares)",
  "Belongs to another society?": "வேறு சங்கத்தில் உறுப்பினரா? (Belongs to another society?)",
  "Other Society Name": "மற்ற சங்கத்தின் பெயர் (Other Society Name)",
  "Digital Documents": "டிஜிட்டல் ஆவணங்கள் (Digital Documents)",
  "Photograph": "புகைப்படம் (Photograph)",
  "Digital Signature": "டிஜிட்டல் கையொப்பம் (Digital Signature)",
  "Digital Signature": "டிஜிட்டல் கையொப்பம் (Digital Signature)",
  "Processing...": "செயலாக்கப்படுகிறது... (Processing...)",
  "Save Changes": "மாற்றங்களைச் சேமிக்க (Save Changes)",
  "Authorize & Register": "அங்கீகரித்து பதிவுசெய்க (Authorize & Register)",
  "Accounts for": "கணக்குகள் (Accounts for)",
  "No accounts found": "கணக்குகள் எதுவும் கிடைக்கவில்லை (No accounts found)",
  "Savings Accounts": "சேமிப்பு கணக்குகள் (Savings Accounts)",
  "Fixed Deposits": "நிலையான வைப்புத்தொகைகள் (Fixed Deposits)",
  "Loan Accounts": "கடன் கணக்குகள் (Loan Accounts)",
  "Pawning": "அடகு (Pawning)",
  "නිකුත් කර ඇත (Active)": "வழங்கப்பட்டுள்ளது (Active)",
  "අනුමැතිය අපේක්ෂාවෙන් (Pending)": "அனுமதி நிலுவையில் உள்ளது (Pending)",
  "ක්ෂුද්‍ර ණය": "நுண் கடன் (Micro Loan)",
  "සාමාන්‍ය ණය": "சாதாரண கடன் (Normal Loan)",
  "විශේෂ ණය": "விசேட கடன் (Special Loan)",
  "දේපල ණය": "சொத்துக் கடன் (Property Loan)",
  "කෙටි කාලීන ණය": "குறுகிய காலக் கடன் (Short Term Loan)",
  "සේවක ණය": "ஊழியர் கடன் (Staff Loan)",
  "ස්ථාවර තැන්පතු විස්තර": "நிலையான வைப்பு விவரங்கள் (Fixed Deposit Details)",
  "ගිණුම් අංකය:": "கணக்கு எண்: (Account No:)",
  "අයදුම්පත": "விண்ணப்பம் (Application)",
  "කුවිතාන්සිය": "ரசீது (Receipt)",
  "මුද්‍රණය කරන්න": "அச்சிடுக (Print)",
  "තැන්පතු කාණ්ඩය (CATEGORY)": "வைப்பு வகை (CATEGORY)",
  "කාලය (TERM)": "காலம் (TERM)",
  "මාස (Months)": "மாதங்கள்",
  "ගිණුම් වර්ගය (ACCOUNT TYPE)": "கணக்கு வகை (ACCOUNT TYPE)",
  "තනි ගිණුමක් (Individual)": "தனிநபர் கணக்கு (Individual)",
  "හවුල් ගිණුමක් (Joint)": "கூட்டுக் கணக்கு (Joint)",
  "සාමාජිකයා (MEMBER)": "உறுப்பினர் (MEMBER)",
  "සම්පූර්ණ නම": "முழுப் பெயர் (Full Name)",
  "මුලකුරු සමඟ නම": "முதலெழுத்துக்களுடன் பெயர் (Name with Initials)",
  "ජාතික හැඳුනුම්පත් අංකය": "தேசிய அடையாள அட்டை எண் (NIC)",
  "උපන් දිනය (DATE OF BIRTH)": "பிறந்த தேதி (DATE OF BIRTH)",
  "දුරකථන අංකය (PHONE NUMBER)": "தொலைபேசி எண் (PHONE NUMBER)",
  "ලිපිනය": "முகவரி (Address)",
  "සාමාන්‍ය ස්ථාවර": "சாதாரண நிலையான (Normal Fixed)",
  "ළමා ස්ථාවර": "சிறுவர் நிலையான (Child Fixed)",
  "ජ්‍යෙෂ්ඨ පුරවැසි": "மூத்த குடிமக்கள் (Senior Citizen)",
  "1. සාමාජික විස්තර (Member Details)": "1. உறுப்பினர் விவரங்கள் (Member Details)",
  "2. තැන්පතු විස්තර (Deposit Details)": "2. வைப்பு விவரங்கள் (Deposit Details)",
  "ගිණුම් අංකය (ACCOUNT NUMBER)": "கணக்கு எண் (ACCOUNT NUMBER)",
  "තැන්පතු මුදල (PRINCIPAL AMOUNT)": "வைப்புத் தொகை (PRINCIPAL AMOUNT)",
  "පොලිය ගෙවන ආකාරය (INTEREST PAYOUT)": "வட்டி செலுத்தும் முறை (INTEREST PAYOUT)",
  "කල් පිරුණු පසු උපදෙස් (MATURITY INSTRUCTION)": "முதிர்வு வழிகாட்டுதல் (MATURITY INSTRUCTION)",
  "සම්බන්ධිත ඉතිරිකිරීමේ ගිණුම (LINKED SAVINGS ACCOUNT)": "இணைக்கப்பட்ட சேமிப்பு கணக்கு (LINKED SAVINGS ACCOUNT)",
  "3. කාර්යාලීය ප්‍රයෝජනය සඳහා පමණි (Office Use Only)": "3. அலுவலக பயன்பாட்டிற்கு மட்டும் (Office Use Only)",
  "කුවිතාන්සි අංකය (RECEIPT NO)": "ரசீது எண் (RECEIPT NO)",
  "තැන්පත් කළ දිනය (DEPOSIT DATE)": "வைப்புத் தேதி (DEPOSIT DATE)",
  "කල්පිරෙන දිනය (MATURITY DATE)": "முதிர்வு தேதி (MATURITY DATE)",
  "පොලී අනුපාතිකය (INTEREST RATE)": "வட்டி வீதம் (INTEREST RATE)",
  "බදු ආකෘති පත්‍රය (TAX FORM)": "வரிப் படிவம் (TAX FORM)",
  "මාසිකව": "மாதாந்திர (Monthly)",
  "කල් පිරීමේදී": "முதிர்வின் போது (At Maturity)",
  "මූලික මුදල සහ පොළිය නැවත ආයෝජනය කරන්න": "அசல் மற்றும் வட்டியை மீண்டும் முதலீடு செய்யவும்",
  "මූලික මුදල නැවත ආයෝජනය කර පොළිය ගෙවන්න": "அசலை மீண்டும் முதலீடு செய்து, வட்டியைச் செலுத்தவும்",
  "කල් පිරුණු පසු ගිණුම වසා දමන්න": "முதிர்வின் போது கணக்கை மூடவும்",
  "තැන්පත්කරුගේ අත්සන": "வைப்பாளரின் கையொப்பம் (Depositor's Signature)",
  "තත්වය": "நிலை",
  "ක්‍රියාකාරී": "செயலில்",
  "කල් පිරීමට ආසන්නයි": "விரைவில் முதிர்ச்சியடைகிறது",
  "අක්‍රියයි": "செயலற்றது",
  "වසා ඇත": "மூடப்பட்டது",
  "කල් පිරී ඇත": "முதிர்ச்சியடைந்தது",
  "(වා.පො.)": "(ஆண்டு வட்டி)",
  "දින": "நாட்கள்",
  "කින් කල්පිරේ": "இல் முதிர்ச்சியடைகிறது",
  "කල්පසු ණයක් ලෙස සලකුණු කරන්න": "தவறிய கடனாகக் குறிக்கவும் (Mark as defaulted)",
  "📋 දළ විශ්ලේෂණය (Overview)": "📋 கண்ணோட்டம் (Overview)",
  "📅 ණය සැලසුම (Schedule)": "📅 கடன் அட்டவணை (Schedule)",
  "💵 වාරික ගෙවීම් (Payments)": "💵 தவணை கொடுப்பனவுகள் (Payments)",
  "📜 අනුමත ඉතිහාසය (History)": "📜 அனுமதி வரலாறு (History)",
  "ඉල්ලුම් කළ මුදල": "கோரப்பட்ட தொகை (Requested Amount)",
  "කාල සීමාව": "கால எல்லை (Duration)",
  "පොලී අනුපාතය": "வட்டி வீதம் (Interest Rate)",
  "ණය වර්ගය": "கடன் வகை (Loan Type)",
  "අයදුම් කළ දිනය": "விண்ணப்பித்த தேதி (Applied Date)",
  "ශාඛාව": "கிளை (Branch)",
  "වාර්ෂිකව": "ஆண்டுக்கு (Annually)",
  "මාසික මූලික මුදල": "மாதாந்திர அடிப்படைத் தொகை (Monthly Principal)",
  "+ මාසික පොලිය (ඇස්ත.)": "+ மாதாந்திர வட்டி (மதிப்பீடு) (+ Monthly Interest (Est.))",
  "= මාසික වාරිකය": "= மாதாந்திர தவணை (= Monthly Installment)",
  "සූත්‍රය: පොලිය = (මූලික මුදල × දින ගණන × අනුපාතය%) ÷ 36,500": "சூத்திரம்: வட்டி = (அசல் × நாட்கள் × வீதம்%) ÷ 36,500",
  "රු.": "ரூ. (Rs.)"
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('si'); // Default to Sinhala

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'si' : 'en'));
  };

  const t = (key: string): string => {
    if (language === 'ta' && tamilDict[key]) {
      return tamilDict[key];
    }
    if (!translations[key]) {
      return key; // Fallback
    }
    return (translations[key] as any)[language] || translations[key]['en'] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
