with open('src/context/LanguageContext.tsx', 'r', encoding='utf-8') as f:
    content = f.read()

new_tamil_dict = """const tamilDict: Record<string, string> = {
  "HMCS Banking": "HMCS வங்கி (HMCS Banking)",
  "Secure Portal Access": "பாதுகாப்பான போர்டல் அணுகல் (Secure Portal Access)",
  "Username": "பயனர் பெயர் (Username)",
  "Password": "கடவுச்சொல் (Password)",
  "Sign In to Secure Portal": "உள்நுழையவும் (Sign In)",
  "Enter your username": "பயனர் பெயரை உள்ளிடவும் (Enter Username)",
  "Authenticating...": "உறுதிப்படுத்தப்படுகிறது... (Authenticating...)",
  "Hikkaduwa Multi-Purpose Co-operative Society Ltd.": "ஹிக்கடுவ பல்நோக்கு கூட்டுறவு சங்கம் லிமிடெட் (HMCS)",
  "© 2026 INTEGRATED BANKING SYSTEM": "© 2026 ஒருங்கிணைந்த வங்கி அமைப்பு (Integrated Banking)",
  "Hikkaduwa Branch": "ஹிக்கடுவ கிளை (Hikkaduwa Branch)",
  "Dodanduwa Branch": "தொடந்துவ கிளை (Dodanduwa Branch)",
  "Rathgama Branch": "ரத்கம கிளை (Rathgama Branch)",
  "Seenigama Branch": "சீனிகம கிளை (Seenigama Branch)",
  "Thiranagama Branch": "திரணகம கிளை (Thiranagama Branch)",
  "Peraliya Branch": "பெரலிய கிளை (Peraliya Branch)",
  "Kalupe Branch": "கலுபே கிளை (Kalupe Branch)",
  "Gonapinuwala Branch": "கோனாபினுவல கிளை (Gonapinuwala Branch)",
  "Dodangoda Branch": "தொடாங்கொட கிளை (Dodangoda Branch)",
  "Baddegama Main Branch": "பத்தேகம பிரதான கிளை (Baddegama Branch)",
  "Galle Main Branch": "காலி பிரதான கிளை (Galle Branch)",
  "සන්දරවල ශාඛාව": "சந்தரவல கிளை (Sandarawala Branch)",
  "පැරෑලිය ශාඛාව": "பெரலிய கிளை (Peraliya Branch)",
  "Dashboard": "டாஷ்போர்டு (Dashboard)",
  "Total Members": "மொத்த உறுப்பினர்கள் (Total Members)",
  "Active Members": "செயலில் உள்ள உறுப்பினர்கள் (Active Members)",
  "Total Accounts": "மொத்த கணக்குகள் (Total Accounts)",
  "Account No.": "கணக்கு எண் (Account No.)",
  "Type": "வகை (Type)",
  "Balance": "இருப்பு (Balance)",
  "Status": "நிலை (Status)",
  "Member": "உறுப்பினர் (Member)",
  "Action": "செயல்பாடு (Action)",
  "Open Account": "கணக்கு ஆரம்பிக்கவும் (Open Account)",
  "Register Member": "உறுப்பினர் பதிவு (Register Member)",
  "Deposit Cash": "பணம் வைப்பு (Deposit Cash)",
  "Withdraw Cash": "பணம் திரும்பப் பெறல் (Withdraw Cash)",
  "Welcome back": "மீண்டும் வருக (Welcome back)",
  "Sign Out": "வெளியேறவும் (Sign Out)",
  "Branch Online": "கிளை ஆன்லைன் (Branch Online)",
  "Reference ID": "குறிப்பு ஐடி (Reference ID)",
  "Amount": "தொகை (Amount)",
  "Balance After": "இருப்பு பின் (Balance After)",
  "Account Owner": "கணக்கு உரிமையாளர் (Account Owner)",
  "Branch": "கிளை (Branch)",
  "Timestamp": "நேரம் (Timestamp)",
  "Close": "மூடவும் (Close)",
  "Deposit": "வைப்பு (Deposit)",
  "Withdrawal": "திரும்பப் பெறல் (Withdrawal)",
  "DEPOSIT": "வைப்பு (Deposit)",
  "WITHDRAWAL": "திரும்பப் பெறல் (Withdrawal)",
  "NEW_SAVINGS": "புதிய சேமிப்புக் கணக்கு (New Savings)",
  "NEW_FD": "புதிய நிலையான வைப்பு (New FD)",
  "Activity Details": "நடவடிக்கை விவரங்கள் (Activity Details)",
  "Confirm Transaction": "பரிவர்த்தனையை உறுதிப்படுத்தவும் (Confirm Transaction)",
  "Confirm": "உறுதிப்படுத்தவும் (Confirm)",
  "Cancel": "ரத்துசெய் (Cancel)",
  "Next": "அடுத்தது (Next)",
  "OPENED DATE": "ஆரம்பிக்கப்பட்ட தேதி (Opened Date)",
  "Opened Date": "ஆரம்பிக்கப்பட்ட தேதி (Opened Date)",
  "Maturity Date": "முதிர்வு தேதி (Maturity Date)",
  "Interest Rate": "வட்டி விகிதம் (Interest Rate)",
  "Principal Amount": "அசல் தொகை (Principal Amount)",
  "FD Number": "நிலையான வைப்பு எண் (FD Number)",
  "FD No": "நிலையான வைப்பு எண் (FD No)",
  "Category": "வகை (Category)",
  "Term": "காலம் (Term)",
  "Account Type": "கணக்கு வகை (Account Type)",
  "Individual": "தனி நபர் (Individual)",
  "Joint": "கூட்டுக் கணக்கு (Joint)",
  "Search Member": "உறுப்பினரைத் தேடு (Search Member)",
  "ගිණුම පවතින ශාඛාව": "கணக்கு இருக்கும் கிளை (Branch)",
  "සමන්ත සෙනෙෂ්": "சமந்த செனேஷ் (Samantha Senesh)",
  "Overview": "மேலோட்டம் (Overview)",
  "Users & Members": "உறுப்பினர்கள் (Members)",
  "Members": "உறுப்பினர்கள் (Members)",
  "Non-Members": "உறுப்பினர் அல்லாதவர்கள் (Non-Members)",
  "Savings Accounts": "சேமிப்புக் கணக்குகள் (Savings Accounts)",
  "Fixed Deposits": "நிலையான வைப்புகள் (Fixed Deposits)",
  "Loan Accounts": "கடன் கணக்குகள் (Loan Loans)",
  "Pawning (Gold Loans)": "அடகு (Pawning)",
  "Cash Transactions": "பணப் பரிவர்த்தனைகள் (Cash Transactions)",
  "General Ledger": "பொதுப் பேரேடு (General Ledger)",
  "Interest Rates": "வட்டி விகிதங்கள் (Interest Rates)",
  "CUSTOMER RELATIONS": "வாடிக்கையாளர் உறவுகள் (Customer Relations)",
  "CORE BANKING FACILITIES": "முக்கிய வங்கிச் சேவைகள் (Core Banking)",
  "DAILY OPERATIONS": "தினசரி செயல்பாடுகள் (Daily Operations)",
  "INFORMATION": "தகவல் (Information)"
};"""

# Let's locate tamilDict in the file and replace it.
# We will use python regex to find const tamilDict = { ... }; and replace it.
import re
pattern = r"const tamilDict: Record<string, string> = \{.*?\};"
content_modified = re.sub(pattern, new_tamil_dict, content, flags=re.DOTALL)

with open('src/context/LanguageContext.tsx', 'w', encoding='utf-8') as f:
    f.write(content_modified)

print("Updated tamilDict with dual Tamil + English labels.")
