spring.application.name=hmcs-loan-service

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/hmcs_db
spring.datasource.username=hmcs_app
spring.datasource.password=hmcs_secure_pass_2026
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate configurations
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Use member_service schema by default
spring.jpa.properties.hibernate.default_schema=loan_service

# Server port
server.port=8084
server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never



hmcs.app.jwtExpirationMs=86400000
spring.jpa.properties.hibernate.tenant_identifier_resolver=com.hmcs.loan.multitenancy.TenantIdentifierResolver

logging.file.name=/var/logs/hmcs/${spring.application.name}.log


jwt.secret=hmcs_secret_key_for_jwt_token_2026_hikkaduwa_bank_management_system
