logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: "${JWT_SECRET}"

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hmcscoopsystem@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true
