spring.application.name=hmcs-api-gateway

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/hmcs_db
spring.datasource.username=hmcs_app
spring.datasource.password=hmcs_secure_pass_2026
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate configurations
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Use account_service schema by default
spring.jpa.properties.hibernate.default_schema=public

# Server port
server.port=8080


hmcs.app.jwtExpirationMs=86400000


