name: Deploy SL CERT Compliant HMCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH for Remote Deployment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

      - name: Deploy to Primary Server (Singapore)
        env:
          DOCKER_HOST: ssh://root@143.198.211.244
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          docker compose --project-name hmcs-bank up -d --build

      - name: Deploy to DR Server (Bangalore)
        env:
          DOCKER_HOST: ssh://root@168.144.216.11
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          docker compose --project-name hmcs-bank up -d --build
